### ISSUE TITLE
implement cluster restore from WAL backup

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#1169]
try restoring cluster from WAL backup
write a guide on how to do that manually

**Comment by stepashka** [comment]
also relates to #1168

**Comment by knizhnik** [comment]
I think some discussion is needed here.
Right now we are not storing WAL from the very beginning.
So it is not possible to run pg_waldump on the first WAL segment:
```
pg_waldump 000000010000000000000001
pg_waldump: fatal: could not find a valid record after 0/1000000
```
It is necessary to inspect metadata file to determine initdb_lsn:
```
~/zenith.main/target/release/update_metadata ~/zenith.main/.zenith/tenants/1c01d03e9de65a1b3bf8df2300a5a82e/timelines/5ab7a3d50e2b7d098d6ab4bd9e3e5cd3/metadata 
Current metadata:
TimelineMetadata { disk_consistent_lsn: 0/169E130, prev_record_lsn: None, ancestor_timeline: None, ancestor_lsn: 0/0, latest_gc_cutoff_lsn: 0/169E060, initdb_lsn: 0/169E060 }
```

and ... still pg_waldump is skipping this record:
```
pg_waldump -s 0/169E060 000000010000000000000001
first record is after 0/169E060, at 0/169E0D8, skipping over 120 bytes
rmgr: XLOG        len (rec/tot):     54/    54, tx:          0, lsn: 0/0169E0D8, prev 0/0169E060, desc: PARAMETER_CHANGE max_connections=100 max_worker_processes=8 max_wal_senders=10 max_prepared_xacts=0 max_locks_per_xact=64 wal_level=replica wal_log_hints=on track_commit_timestamp=off
```

Right now we initialize database in some temporary directory, then create pageserver repository from it and to intialize comute node pageserver creates tarball without WAL but with pg_control file with checkpoint record which points to the last LSN.

So to get consistent WAL we can initialize some new dummy database and copy begging of first WAL segment from its directory. But it seems to be very error prone. Database initialization depends on many parameter. And there is no warranty that if we want to restore database which was created some time ago, we will get exactly the same database and WAL image.

It seems to be safer to grab first WAL segment when database is initialized and save it somewhere... But where? In pagestore repository? But it means that we can not restore cluster without pageserver repository. It will be better to somehow deliver missed data to computer and through it to safekeepers. So should we include this first WAL segment in tarball? This is what we have started with and later removed. But then we need to distinguish cluster intitialization and restart

**Comment by knizhnik** [comment]
May be I missed something, but looks like the approach with creating new database and apply WAL achieve to it doesn't work. Each WAL segment contains sysremid and if it doesn't match then Postgres stops recovery.
initdb creates database with new systemid, so WAL from other database can not be applied to it.

Old versions of Postgres (7.*) allows to specify systemid in initdb. But right now it is not possible.
So the following approach:
1. Create databae using initdb
2. Copy head of WAL segment from this new database to first WAL segment of safekeeper (filling hole in this segment)
3. Copy WAL from safekeeper to pg_wal directory (or use archive recovery command instead)
4. Force Postgres to perform recovery and reply WAL 

restores only first WAL segment and stop after it, because all other segments has wrong systemid.

In theory we can extract systemid from saved WAL, copy it to pg_control file and single WAL segment of the new database, recalculate checksums for pg_control file and checkpoint record. But it seems to be very ugly and error prone solution, doesn't it?

So I think we should make basebackup of initialized database and store it somewhere to be able to use it for recovery in case of data lost or corruption.

**Comment by knizhnik** [comment]
Just read the thread about make it possible to reset systemid usig pg_resetxlog(now pg_resetwal) utility:

https://postgrespro.com/list/thread-id/1846052

One of the last messages in this thread was @hlinnaka vote against it;)

**Comment by hlinnaka** [comment]
> Just read the thread about make it possible to reset systemid usig pg_resetxlog(now pg_resetwal) utility:
> 
> https://postgrespro.com/list/thread-id/1846052
> 
> One of the last messages in this thread was @hlinnaka vote against it;)

:-) My position was a bit more nuanced than that. My point was (and is) that we don't want DBAs to run pg_resetxlog as part of daily operations, or as part of regular scripts. If there's a use case for changing system id in normal operations, we should add a new utility for it, or at least clearly document which pg_resetwal options are dangerous and can eat your data, and which ones are not. As a disaster recovery thing, adding it to pg_resetwal is fine, but then it should come with the same warnings as the other pg_resetwal options.

**Comment by knizhnik** [comment]
See https://github.com/zenithdb/postgres/pull/124

I have patched initdb to take --sysid parameter.
With this patch it is possible to create database from WAL stored at safekeepers using one of the provided scripts:

`contrib/zenith/utils/restore_from_wal_archive.sh` 
is creating temporary directory, copying WAL files in it and perform archive recovery. It will be not so difficult to change this script to grab WAL files directly from safekeepr.

`contrib/zenith/utils/restore_from_wal.sh` doesn't create temporary directory.
It copies WAL files directly to target database pg_wal directory
and then ise immediate shutdown to force recovery. 

Both scripts extract systemid from second WAL segment (assuming that it exists, because restoring almost empty database makes not so much sense).
But systemid can be also extracted from mane other places: pg_control, checkpoint record,...

Also them are using hardcoded offset of initdb WAL position: 6924704.
It can be definitely changed in future. It is possible to check initdb location in metadata file using `update_metadata` utility. Or use pg_waldup to locate it.

**Comment by knizhnik** [comment]
Example of restoring WAL:
```
./vendor/postgres/contrib/zenith/utils/restore_from_wal.sh .zenith/safekeepers/single/94f611570145fa549dca7b1fd91fdda6
```

**Comment by kelvich** [comment]
Doesn't work again: `2022-03-14 18:24:49.276 +04 [1975] LOG:  invalid record length at 0/16B5678: wanted 24, got 0
`
Hardcoded paths (/home/knizhnik/zenith.main/tmp_install/) make it hard and time consuming to check.

I suggest to do following:

* commit `--sysid` initdb option as it is harmless anyway.
* ditch whole bash scripts approach. They don't belong to that repo. Let's write python recovery test in zenith repo instead.

When we know that test is working we can write a standalone script.
