### ISSUE TITLE
cannot cancel pgbench init when running via proxy

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#1213]
I was able to cancel the workload, but not the init phase. It worked for the local configuration without proxy

**Comment by bojanserafimov** [comment]
I couldn't reproduce this. Were you using any flags other than what I have [here](https://github.com/zenithdb/zenith/blob/2eb26206565997f9bc21173ef20e3ca436636c85/test_runner/batch_others/test_proxy.py#L43)?

**Comment by LizardWizzard** [comment]
Hm, maybe it was some lucky timing, or a very slow connection. Yesterday I tried to run pgbench from Moscow against our production cluster in US and saw this behaviour, I'll recheck this and try to get some insights from digging into actual network traffic

**Comment by stepashka** [comment]
it's in your hands, @LizardWizzard  :)

**Comment by LizardWizzard** [comment]
I was able to reproduce it with `pgbench -i -s500`. I hit Ctrl+C after around a second

I'm using mobile internet connection so it may cause problems:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/19991702/157741438-eadb2409-29f3-41bd-b6ca-e696283a83e6.png">

I think it may be a problem with pgbench itself. I'm running wireshark and I can see cancel requests being sent, but I see new queries too which is odd. I'll try to dig deeper

**Comment by LizardWizzard** [comment]
Yeah, I think I've found the reason. When pgbench initializes small tables (pgbench_branches, pgbench_tellers) there is no cancellation handler. So when internet connection is really bad population of these small tables can take significant time. 

Following patch fixes the problem for me:

```diff
diff --git a/src/bin/pgbench/pgbench.c b/src/bin/pgbench/pgbench.c
index d2c0ed3dfc..e88cc4b17e 100644
--- a/src/bin/pgbench/pgbench.c
+++ b/src/bin/pgbench/pgbench.c
@@ -4189,6 +4189,8 @@ initGenerateDataClientSide(PGconn *con)
 						  "insert into pgbench_branches(bid,bbalance) values(%d,0)",
 						  i + 1);
 		executeStatement(con, sql.data);
+		if (CancelRequested)
+			break;
 	}
 
 	for (i = 0; i < ntellers * scale; i++)
@@ -4198,6 +4200,8 @@ initGenerateDataClientSide(PGconn *con)
 						  "insert into pgbench_tellers(tid,bid,tbalance) values (%d,%d,0)",
 						  i + 1, i / ntellers + 1);
 		executeStatement(con, sql.data);
+		if (CancelRequested)
+			break;
 	}
 
 	/*
```

@hlinnaka what do you think? should it be submitted upstream or this can be ignored due to insignificance?

**Comment by hlinnaka** [comment]
Yeah, whatever we do here, we should do it in upstream.

I'm confused by the one CancelRequested check that there is now. If you hit CTRL-C, it will cancel the data generation, but still proceeds with the steps after that like creating indexes, and reports "done in x s". I would expect some kind of an error message, and non-zero exit status. This query cancellation logic was added by commit 1d468b9ad81b9139b4a0b16b416c3597925af4b0, before that it worked the way I'd expect: if you hit CTRL-C, pgbench exits immediately. I think what that commit tried to do is to also cancel the possibly-long running query in the server, to avoid wasting server resources, especially if you're using server-side generation of the data with `pgbench -I dtGvp -s100 -i`. But it accidentally changed it so that the pgbench client doesn't exit immediately on CTRL-C anymore. In short, I think 1d468b9ad81b9139b4a0b16b416c3597925af4b0 was broken.

So I don't think the proposed patch that adds CancelRequested is the right fix. Perhaps call setup_cancel_handler() with a callback that does exit() (is that safe from a signal handler? I don't remember). Except that currently the callback gets called *before* sending the query cancel to the server, and we'd want the exit() to happen after the cancellation. Or perhaps sprinkle those CancelRequested checks like you proposed, but we'll need to have them in more places, and exit() when it happens.

But yeah, please open a thread on this on pgsql-hackers.

**Comment by LizardWizzard** [comment]
> it will cancel the data generation, but still proceeds with the steps after that like creating indexes, and reports "done in x s"

Yeah, that felt strange for me too. 

Thanks! I'll improve the patch and open a thread on hackers

**Comment by dhammika** [comment]
This is probably from `-i` flag, that sets a SIGINT handler.
https://github.com/zenithdb/postgres/blob/a260728984e27137130681ab24fa83a4f4815c4e/src/bin/pgbench/pgbench.c#L4451

That tries to send a query cancel and it's pretty heavy, QueryCancel's connect(), send() and recv() all can block ie. pkt drops in the network or just blocking ingress pkts from the db. 
https://github.com/zenithdb/postgres/blob/a260728984e27137130681ab24fa83a4f4815c4e/src/interfaces/libpq/fe-connect.c#L4412-L4541

**Comment by hlinnaka** [comment]
@MMeent could you take a look at this please? PostgreSQL v16 feature freeze has started, so now is a good time to work on bug fixes rather than features :-).

**Comment by knizhnik** [comment]
Just noticed that after termination `pgbench_accounts` contains just one record, because check for `CancelRequested` is done after generation of first record.

I do not see any PR with proposed fix of this problem at commitfest, did we created one?

I do not think that calling exit from signal handler is goof idea because according to the specification it is not one of the async-signal-safe functions. It is possible to call `_exit` or `_abort`. From my point of view it is enough just to add printing message at the end that initialization of the database  was canceled.

There is another related problem: with slow connection `pgbench -i` takes at lot of time just because each teller is created using separate insert statement so with larger roundtrip even with scale 100, initialization of 1000 tellers may take too much time The obvious solution is to use COPY for initialization of this table just as `pbench_account`. But I am not sure how useful such optimization  may be, taken in account that main pgbench test will send individual statements in any case, so with ~1 sec latency reported performance will be awful. So it is not clear do we need to speed-up initialization if main benchmark loop will still suffer from this problem.

**Comment by hlinnaka** [comment]
The easiest way to reproduce is to use a ridiculously large scale. With a large scale, the `initGenerateDataClientSide` function takes a long time so that it's easier to see the problem:
```
$ pgbench -i -s500000 postgres
dropping old tables...
creating tables...
generating data (client-side)...
[hit CTRL-C]
^CCancel request sent
[pgbench keeps running]
```

**Comment by tristan957** [comment]
Update: I have a patch I am pretty comfortable with. I will be submitting it to the mailing list on Monday probably.

**Comment by hlinnaka** [comment]
I was browsing through old emails to pgsql-bugs list, and saw this thread that's tangentially related: https://www.postgresql.org/message-id/17698-58a6ab8caec496b0%40postgresql.org

**Comment by tristan957** [comment]
I can respond to the thread if you want. Seems like a _simple_ patch given the framework of `fe_utils/cancel.h` already.

**Comment by tristan957** [comment]
Dropping a link to the mailing list entry: https://www.postgresql.org/message-id/CSSWBAX56CVY.291H6ZNNHK7EO@c3po
