### ISSUE TITLE
Materialize and garbage collect pages during compaction

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1355]
We don't currently try to materialize pages or garbage collect anything during compaction. If the GC horizon is short, that would save a lot of effort, as you could get rid of old garbage instead of "reshuffling" it in the level 0.

**Comment by knizhnik** [comment]
Sorry, I do not completely understand this ticket.
We actually DO materialize pages during compaction:
```
           // 2. Create new image layers for partitions that have been modified
            // "enough".
            for part in parts.iter() {
                if self.time_for_new_image_layer(part, lsn, 3)? {
                    self.create_image_layer(part, lsn)?;
                }
            }
```

My question is it really good idea to combine repartitioning (it is more correct term than "compaction" , isn't it?) with materialization (page reconstruction).

Or do you mean that after image layer creation we may not need to perform shuffling of delta layers at all, because them can be garbage collected as been out of PITR interval?
But if PITR is expected to be one of our key features (including PITR from S3), then looks like probability of such scenario is small.

**Comment by knizhnik** [comment]
See https://github.com/zenithdb/zenith/pull/1408

**Comment by jcsp** [comment]
Cleaning up old tickets
