### ISSUE TITLE
Safekeepers sync is slow when EC2 safekeeper instance is down

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#1491]
Cluster `bold-pond-326774` from staging had a failed operation `start_compute` at Apr 12, 2022 12:35 PM (GMT+3). Seems that operation failed because safekeepers syncing took more than 2 minutes. [logs](https://observer.zenith.tech/d/IJSLHBOnk/zenith-logs-compute-nodes?orgId=1&var-environment=staging&var-instance=All&var-search=bold-pond-326774&var-exclude=assign%20requested&from=1649756018244&to=1649757002651)

My theory is that we have a problem somewhere near `--sync-safekeepers` exit criteria:
https://github.com/neondatabase/postgres/blob/61afbf978b17764134ab6f1650bbdcadac147e71/src/backend/replication/walproposer.c#L2016-L2018

More specifically, we're waiting for safekeeper in connecting state until TCP timeout happens. This is not reproduced in tests because localhost is always up.

**Comment by arssher** [comment]
Since walproposer uses libpq in async way, we should manually implement `connect_timeout` behaviour of libpq. Or just wait for pageserver to choose safekeeper to fetch WAL from properly.

For the record, currently this occurs on old clusters in staging because they try to reach dead safekeeper as their config is not updated.
