### ISSUE TITLE
Many commits show red statuses with red pipelines

### ISSUE THREAD

**Issue by karuppiah7890** [neondatabase/neon#1669]
Looking at the commits in https://github.com/neondatabase/neon/commits/main , many commits show a red cross symbol like ❌ and a few show green tick symbol like ✅ . Looks like there were a few red pipelines in some of these commits. The latest commit as of this writing shows a green status but I'm not sure if it's all fixed or if the mix of red and green are pointing to a flaky pipeline of sorts which needs fix to avoid flakiness

**Comment by SomeoneToIgnore** [comment]
We sure do notice ❌ and failures and are working on fixing those.
The fix for recent failures can be tracked here: https://github.com/neondatabase/neon/issues/1667

Unfortunately, there are many moving parts that we change constantly and we have lots of tests, so some of those start to flack with time, I think it's normal generally if the source issue is being investigated and fixed.
Some of our tests are also a bit complicated from the infrastructural point of view, failing non on the test per se, but on persisting its results externally (as an extra step after "normal" testing).

Not sure what to add to such generic issue, so closing this.
If you have any other particular questions (maybe, some failing tests you're interested with?), feel free to create more specific issues or commenting on this one.

**Comment by karuppiah7890** [comment]
Makes sense! Sure thing :)
