### ISSUE TITLE
Update our PostgreSQL to version 14.3

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1675]
It is released on Thursday May 12th.

**Comment by phoenix24** [comment]
just curious, is this a good-first-issue?

**Comment by SomeoneToIgnore** [comment]
Wort a try, could be simple.

We have a set of patches on top of Postgres, presumably all rebased on top of a fixed Postgres commit.
One updating the version, need to rebase those on top and those might even not conflict (then it's a simple task), otherwise it might get more interesting.

See https://github.com/neondatabase/neon/issues/1236 as one of the examples of such work done in the past.

**Comment by hlinnaka** [comment]
I think for now, we should not try to rebase the patches. Rebasing is a lot of effort, as you need to rearrange the patches so that each patch is a logical, self-contained set of changes. For now, let's just do `git merge pgsql/REL_14_3`. That should indeed not be too hard.

**Comment by phoenix24** [comment]
thanks much @hlinnaka  @SomeoneToIgnore, i'd give it a shot.

**Comment by phoenix24** [comment]
@hlinnaka I think this has already been addressed [here](https://github.com/neondatabase/neon/commit/b10ae195b78835ba895d90ccc1573a0a018d8a28). can you confirm if i got that right?

**Comment by hlinnaka** [comment]
14.4 was merged some time ago already, closing.
