### ISSUE TITLE
Give better instructions if client is missing SNI support

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#1745]
If you try to connect with a client that doesn't support SNI, you get:
```
ERROR:  SNI info is missing, please upgrade the postgres client library
```
Let's add a HINT or something, for how to either:
- upgrade libpq, or
- use query parameters to specify the project name

See https://github.com/neondatabase/neon/blob/main/docs/rfcs/016-connection-routing.md#connection-url for how the query parameters would look like. Although I'm not sure if that's been fully implemented in the proxy yet.

**Comment by kelvich** [comment]
Some context for @KlimentSerafimov on how to approach this. To play locally you need:

```sh
# generate keys for TLS-encrupted connections
openssl req -new -x509 -days 365 -nodes -text -out server.crt -keyout server.key -subj "/CN=*.localtest.me"
# start proxy
./target/debug/proxy --auth-backend=console -c server.crt -k server.key
ClientAuthMethod::from_str: 'console'
Version: git:3ff5caf786e666c988c3d74d65e399d95d1b7ae6-modified
Starting http on 127.0.0.1:7001
Starting mgmt on 127.0.0.1:7000
Starting proxy on 127.0.0.1:4432
```

After that you can try to connect to the proxy:

```
psql 'postgres://my-cluster-123.localtest.me:4432/main'
```

You will get an error `Internal error` and proxy log will show something like `error: error sending request for url (http://localhost:3000/authenticate_proxy_request//proxy_get_role_secret?project=my-cluster-123&role=stas): error trying to connect: tcp connect error: Connection refused (os error 61)`. That is okay and simply means that proxy was able to parse cluster name from the SNI info, but wasn't able to connect to the console because it is not running.

To simulate older clients you may disable client SNI:

```
psql 'postgres://my-cluster-123.localtest.me:4432/main?sslsni=0'
```
In this case you will see mentioned `SNI missing error`. And the task here is to make following properly get the cluster name too:

```
psql 'postgres://my-cluster-123.localtest.me:4432/main?sslsni=0&options=cluster:my-cluster-123'
```

Note that startup packet parsing will also ignore `options` field and you'll need to fix that too -- `tcpflow` utility an starting proxy in non-tls mode (omit -k and -s keys) can help here.

**Comment by datduyng** [comment]
> ```shell
> ./target/debug/proxy
> ```

@kelvich can you help me locate the `./target/debug/proxy` file?

**Comment by kelvich** [comment]
> @kelvich can you help me locate the ./target/debug/proxy file?

You can follow build instructions in the top level README. After `cargo build` step `./target/debug/proxy` will appear.
