### ISSUE TITLE
`test_pageserver_http_get_wal_receiver_success` is flaky

### ISSUE THREAD

**Issue by yeputons** [neondatabase/neon#1768]
E.g. see here: https://app.circleci.com/pipelines/github/neondatabase/neon/6589/workflows/8ef21c54-1f2e-4346-98e3-accb4f4f0910/jobs/66732

```
test_runner/batch_others/test_pageserver_api.py:87: in test_pageserver_http_get_wal_receiver_success
    assert res2["last_received_msg_lsn"] > res["last_received_msg_lsn"]
E   TypeError: '>' not supported between instances of 'str' and 'NoneType'
```

My suspicion is that there is no guarantee that a timeline is fully(?) propagated to Pageserver once `env.postgres.create_start` is completed, so it's possible that `env.pageserver.http_client().wal_receiver_get(....)` returns `None` in the `last_received_msg_lsn` field.

If it's the case, who does the propagation? Is it just delayed by local network or is it done by some background thread on timeout? Should we wait for it instead? Should we wait in the `create_start` function itself?

**Comment by hlinnaka** [comment]
> My suspicion is that there is no guarantee that a timeline is fully(?) propagated to Pageserver once `env.postgres.create_start` is completed, so it's possible that `env.pageserver.http_client().wal_receiver_get(....)` returns `None` in the `last_received_msg_lsn` field.

Yeah.

> If it's the case, who does the propagation? Is it just delayed by local network or is it done by some background thread on timeout? Should we wait for it instead? Should we wait in the `create_start` function itself?

Hmm. I don't think `create_start` should wait. It takes a while for a piece of WAL to be propagated from postgres -> safekeeper -> pageserver. And that's ok. The GetPage requests from postgres to pageserver contain the request LSN, and if the pageserver hasn't yet received the WAL up to that LSN, it will do the waiting.

In this test, even if `last_received_msg_lsn` has some value other than None before the CREATE TABLE command, there's no guarantee that it would have advanced in the call after it. Yeah, it makes sense for this test to wait, to check that the value advances.

This reveals another bug in the test, BTW: the error message says that it's trying to compare 'str' with None. We shouldn't be dong string comparison in the first place here, we should convert the LSNs to integers and do an integer comparsion (see `lsn_from_hex`). I've made this mistake a few times myself in the last few weeks; its subtle. Perhaps we should create a Python Lsn datatype for our tests, and register that with psycopg2 so that LSN fields would be automatically converted to the Lsn type (see https://www.psycopg.org/docs/advanced.html#type-casting-of-sql-types-into-python-objects). It wouldn't have helped here, because the LSN value came from the HTTP API rather than from a Postgres query, but still.

**Comment by hlinnaka** [comment]
> I wonder how should we fix this test? Are there any ways to "wait for LSN to be updated" within our test framework?
> We can add a time delay to make sure it's enough for the WAL to be propagated, but I personally don't like this approach as it's not guaranteed and also make our test slower.

Hmm, I think the easiest way is to poll and wait, see `wait_until` in zenith_fixtures.py.
