### ISSUE TITLE
WAL timeouts in pageserver on GetPage@LSN and basebackup

### ISSUE THREAD

**Issue by ololobus** [neondatabase/neon#1885]
There are several failed start_compute operations on staging: https://console.stage.neon.tech/admin/operations?sort=updated_at&order=desc&had_retries=some&action=start_compute

Some `start_compute` that failed on first attempt, but succeeded after the second retry.

Error was:
```log
could not start the compute node: db error: ERROR: could not read block 0 in rel 1663/12972/3467.0 from page server at lsn 0/0169E1C0 DETAIL: page server returned error: Timed out while waiting for WAL record at LSN 0/169E1C0 to arrive, last_record_lsn 0/16960E8 disk consistent LSN=0/16960E8 Caused by: ERROR: could not read block 0 in rel 1663/12972/3467.0 from page server at lsn 0/0169E1C0 DETAIL: page server returned error: Timed out while waiting for WAL record at LSN 0/169E1C0 to arrive, last_record_lsn 0/16960E8 disk consistent LSN=0/16960E8
This project is from e2e, so it dedn't receive any significant load and it's suspicious to see pageserver WAL timeout
```

And the same problem with basebackup:
```
could not start the compute node: failed to get basebackup@0/169E968 from pageserver host=zenith-us-stage-ps-2.local port=6400 Caused by: 0: failed to iterate over archive 1: db error: ERROR: Timed out while waiting for WAL record at LSN 0/169E968 to arrive, last_record_lsn 0/16960E8 disk consistent LSN=0/16960E8 2: ERROR: Timed out while waiting for WAL record at LSN 0/169E968 to arrive, last_record_lsn 0/16960E8 disk consistent LSN=0/16960E8
```

These projects are from e2e, so they didn't receive any significant load and it's suspicious to see pageserver WAL timeouts here.

In logs https://observer.zenith.tech/d/8G011dlnk/timeline-inspector?orgId=1&var-env=aws-staging-us-east-1-zenithdb-01&var-timeline_id=e161a4ef94ac42fca0a47d3950d77a05&var-project_id=&from=now-3h&to=now
I see the same timeouts mostly and
```
2022-06-04T09:01:38.702369Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}:etcd_subscription: Subscribing to timeline updates, subscription kind: SkTimelineSubscriptionKind { broker_etcd_prefix: "neon", kind: Timeline(ZTenantTimelineId { tenant_id: ce7dd8efaf3f87a4353e40dcdbb65247, timeline_id: e161a4ef94ac42fca0a47d3950d77a05 }) }
2022-06-04T09:01:38.702324Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}:etcd_subscription:etcd_broker: Watch for timeline updates subscription was canceled, exiting
2022-06-04T09:01:38.706139Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}: Subscribed for etcd timeline changes, considering walreceiver connections
```

Look on the timestamps:
```
702369Z Subscribing to timeline updates
702324Z Watch for timeline updates subscription was canceled, exiting
706139Z Subscribed for etcd timeline changes
```

According to timestamps subscription was cancelled first and then we re-subscribed, but order of log entries is wrong %) Probably the problem with loki / grafana

Is it some problem with coordination via etcd?

cc @SomeoneToIgnore

**Comment by SomeoneToIgnore** [comment]
Looks like coordination issue indeed, but those cancellations seem a bit suspicious: they come when from the safekeeper side and look odd.

I can look in more details later.

**Comment by arssher** [comment]
I looked at the logs of ce7dd8efaf3f87a4353e40dcdbb65247. Its failed start overlapped with etcd restarts which I did for disabling persistency:

https://observer.zenith.tech/explore?orgId=1&left=%5B%221654333200000%22,%221654333380000%22,%22Loki%22,%7B%22expr%22:%22%7B%20pod%3D~%5C%22etcd.*%5C%22,%20zenith_env%3D%5C%22staging%5C%22%7D%22,%22refId%22:%22A%22,%22range%22:true,%22maxLines%22:4000%7D%5D
(one node started at  09:00:12, another at 09:01:3)

So it could be related, but atm I don't quite believe it is enough to explain what happened. In that case I'd expect to see a lot of failures of pushes to etcd on safekeeper side, but there isn't many:
https://observer.zenith.tech/explore?orgId=1&left=%5B%221654333200000%22,%221654333380000%22,%22Loki%22,%7B%22expr%22:%22%7Bhostname%20%3D~%5C%22.*stage-sk.*%5C%22%7D%20%7C%3D%20%5C%22push%5C%22%22,%22refId%22:%22A%22,%22range%22:true,%22maxLines%22:4000%7D%5D
So it looks like safekeeper successfully pushed data.

Generally the timings look like
```
9:00:29 first attempt to create compute
  T09:00:28 subscribed for etcd timeline...
   WAL receiver without a connection spent sleeping 30s without being interrupted, aborting the loop
   09:00:58 subscribed again
   09:01:08 sub source was dropped, but I don't see related errors. Again broker starts again outer
     loop iter, this time shouting on failing cancel (no wonder).
     Yes, looking at the code sub task swallows the error. Likely error was due to etcd restart.
   09:01:38 again WAL receiver without a connection spent sleeping 30s without being interrupted, aborting the loop
9:01:30 operation aborted
9:01:36 operation restarted
   2022-06-04T09:02:08.099895Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}: Switching to different safekeeper 13 for timeline ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05, reason: NoExistingConnection
   2022-06-04T09:02:08.099977Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}:safekeeper_handle{sk=13}: connecting to    host=zenith-us-stage-sk-4.local port=6500 options='-c ztimelineid=e161a4ef94ac42fca0a47d3950d77a05 ztenantid=ce7dd8efaf3f87a4353e40dcdbb65247'Show context
   2022-06-04T09:02:08.104018Z  INFO wal_receiver_main:timeline{id=ce7dd8efaf3f87a4353e40dcdbb65247/e161a4ef94ac42fca0a47d3950d77a05}:safekeeper_handle{sk=13}:safekeeper_handle_db: connected!
9:02:09 success
```

So for a minute pageserver either didn't receive data from etcd or not reacted to it (not elected safekeeper). The latter seems unlikely, I looked through the code again and and it looks ok in this sense. Also, during this minute pageserver twice recreated subscription: first because of 30s timebomb, second because of connection problem -- watch errored out. There are a couple of problems with that:
- Error from subscription task is never reported.
- Even if subscription task failed, which looks like closed channel at broker task end, broker task still attempts to cancel it -- and gets one more spurious error.
@SomeoneToIgnore This friction between tasks is an illustration of why I'd prefer to avoid separate task (I questioned that in review) without some substantial reasons to have it, and we don't need it here AFAIS.

**Comment by seymourisdead** [comment]
it seems it happened again
https://neondatabase.pagerduty.com/incidents/Q0HH1XHJ6FUQKR
op id: `13aea768-d05d-45cf-bcc6-a24515fe2b88`

**Comment by ololobus** [comment]
We got the same situation on prod tonight: https://neondb.slack.com/archives/C03F5SM1N02/p1655627129866909?thread_ts=1655625880.656499&cid=C03F5SM1N02

Peculiar aspect is that we don't use etcd for coordination on prod yet, so it's likely not related and could be some older problem

**Comment by ololobus** [comment]
I restarted all storage services around 10:30 CEST 19.06 and it helped, so far all e2e rounds passed, while previously ~60-70% of runs were failing

**Comment by shanyp** [comment]
#2106 will handle this case
