### ISSUE TITLE
How to add new tenants and timelines?

### ISSUE THREAD

**Issue by dvaldivia** [neondatabase/neon#1941]
I'm trying to figure out once I get a cluster running with 1 page server and 3 safe keepers, on how to add a tenant so I can get the compute nodes to pick it up.

**Comment by SomeoneToIgnore** [comment]
If you don't control it (i.e. using the Neon website), I have doubts it's possible without contacting the provider.
If you do, check out pageserver's HTTP API: https://github.com/neondatabase/neon/blob/main/pageserver/src/http/openapi_spec.yml

You're able to create the timelines and tenants separately, first a tenant have to be created, later its timeline.
The timelines can be either created from scratch, or reuse old timeline data, as the HTTP API implies.

To simplify things more, we have a CLI utility, `neon_local` that can be used to manage the locally available cluster. It tries to make things a bit more convenient to the users by automatically creating timelines when creating tenants,  but rather crude otherwise.
Check out the [main docs](https://github.com/neondatabase/neon/blob/main/README.md) or the [test code](https://github.com/neondatabase/neon/blob/main/test_runner/fixtures/neon_fixtures.py#L902) that uses this binary for more examples. 

Aside from those two ways, there's not much you can do with the set-up to change its branches or timelines.
Btw, here's a GH discussions place that looks a bit more suitable for questions: https://github.com/neondatabase/neon/discussions

**Comment by dvaldivia** [comment]
what do you mean by contacting the provider? is the `pageserver` the provider?

I tried to add a tenant via the API on the `pageserver` and I keep getting empty responses, while the pageserver returns the following.

```
2022-06-16T15:41:40.455768Z ERROR Thread 'serving Page Service thread' tenant_id: None, timeline_id: None exited with error: invalid message length
```

I may be missing the authorization, but the error doesn't suggest that (perhaps it should return 403)

request

```
curl --location --request POST 'localhost:6400/v1/tenant/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <Bearer Token>' \
--data-raw '{
  "new_tenant_id": "cff554bd-a130-4fd4-a703-92e60f4c9e5c",
  "tenant_id": "cff554bd-a130-4fd4-a703-92e60f4c9e5c"
}'
```

**Comment by dvaldivia** [comment]
@SomeoneToIgnore will `neon_local` work with a deployed cluster? I'm trying to run this on kubernetes

**Comment by SomeoneToIgnore** [comment]
> what do you mean by contacting the provider

The service provider: `neon_local` is capable of connecting to the cluster locally only, when all the components are located on the same FS. If anybody else had provided you the cluster, you're unable to manipulate it with `neon_local` from outside.

> while the pageserver returns the following

Try adding `v1/doc` path to your deployment's basepath to show the swagger UI, e.g. http://localhost:9898/v1/doc for locally started pageserver with default config.
That UI is capable of showing proper request and responses which should help you more than our current json parsing errors. 

> will `neon_local` work with a deployed cluster?

Not, I'm afraid: the current tool was created to ease the local set up and it attempts to access and manage the binaries on the current system, as `_local` prefix tries to imply 🙂 
There's a product for managing the k8s deployments also exists, but currently is in the works and not open. It's also way more complicated than a CLI tool, I'm afraid.

**Comment by LizardWizzard** [comment]
@dvaldivia The error happens because you're trying to reach page server's endpoint dedicated to Postgres protocol. Not HTTP.  Page Service thread serves page requests from the compute node. The API call should succeed if you use HTTP port instead. The default for it is 9898. The setting is controlled via `listen_http_addr` config option in `pageserver.toml`

**Comment by dvaldivia** [comment]
Using port `9898` I was able to add a tenant and a timeline! thanks
