### ISSUE TITLE
Test import of large projects from fullbackup

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#2020]
It is possible, that import checkpoint will generate huge layer file.
We need to make sure that checkpointer, compaction and S3 handle it correctly.

@LizardWizzard

**Comment by SomeoneToIgnore** [comment]
See also 
https://github.com/neondatabase/neon/issues/1910
and 
https://neondb.slack.com/archives/C026T7K2YP9/p1656571026233649

We use PUT requests only when dealing with S3 and those are limited with ~5 GB.

We require the size of the upload in the remote storage API anyway, so we can work on detecting and switching mechanism.

Yet, according to the Slack discussion, we don't plan to have such big files?

**Comment by hlinnaka** [comment]
Hmm, so to summarize the problem, if you import a large database from a physical backup, all the imported page versions will have the same LSN. Our current strategy for avoiding large files is to freeze the in-memory layer roughly every 1 GB (ie. checkpoint_distance). But that doesn't help, if all the data is imported with the same LSN.

A quick solution can be perform "compaction" after the import, to split the large L0 file into multiple smaller L1 files. Even better: when freezing the in-memory layer, write multiple L1 files directly, instead of one L0 file, if the file would be too large.
