### ISSUE TITLE
Deploy SafeKeep and Pageserver separately in different machines

### ISSUE THREAD

**Issue by aqktjcm** [neondatabase/neon#2227]
I would like to test Neon's performance.
The sample in README.md shows how to deploy SafeKeeper and Pageserver locally. Is there any way to deploy multi SafeKeepers and Pageservers in different machines from postgres?

**Comment by arssher** [comment]
Sure. However, `neon_local` doesn't support non-local installation, so you would need to init & run pageserver and safekeepers manually. You can have a look at `.github/ansible/systemd/pageserver|safekeeper.service` for example of running, and `init_pageserver|safekeeper.sh` scripts for init (you don't need console part, so basically running once with `--init` is enough).

Also etcd must run alongside (storage daemons accept its endpoint as an argument).

**Comment by aqktjcm** [comment]
@arssher ，Thanks for your answer.
 
I have started Pageserver and Safekeeper as you said above, but the postgres process cannot start. How do I initialize and start the postgres process without `neon_local`?

**Comment by aqktjcm** [comment]
@arssher ，
When starting the postgres process, timeline_id and tenant_id need to be set in postgresql.conf. How can I obtain the values of these two parameters?

**Comment by arssher** [comment]
The most simple way would be to set them during pageserver init, e.g.
```
../target/debug/pageserver --init -D . -c "id=42" -c "pg_distrib_dir='../tmp_install'" --create-tenant 408ba6d9a4d0db1feedabac91e4619d7 --initial-timeline-id 408ba6d9a4d0db1feedabac91e4619d6
```

Otherwise they tenant/timeline have to be created manually with http calls.

Starting postgres manually is a bit involved, neon_local hides several actions here.
0) Prepare data directory with proper config. See https://github.com/neondatabase/neon/blob/e5cb72757250457a61eeb4bdd7c613527ce7ec98/control_plane/src/compute.rs#L264 for example.
1) Run postgres in special `sync-safekeepers` mode. Can be skipped initially or if services were shut down cleanly (not under load).
2) Get basebackup from pageserver. Manully can be done with something like `psql -h 127.0.0.1 -p 64000 -c 'basebackup 408ba6d9a4d0db1feedabac91e4619d7 408ba6d9a4d0db1feedabac91e4619d6' | tar -C pgdatadir -xvf  -`
3) Then `pg_ctl start -D pgdatadir`

**Comment by px1900** [comment]
Hello @arssher , 

I appreciate your detailed instructions on deploying Neon on multiple nodes. As a Ph.D. student with a keen interest in PostgreSQL and Neon database, I encountered challenges deploying Neon across nodes due to insufficient documentation. It appears that the solution you shared a year ago may not align with the current Neon version.

I would be grateful if you could give our Neon beginners some guidances on deploying compute nodes, pageservers, and safekeepers across distinct nodes in current version.

Thank you.
