### ISSUE TITLE
Make WAL recovery go faster by prescanning the WAL

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#240]
Imagine that you have a 1000 WAL records updating the same page, and finally at the end one more WAL record with a full-page image of it. It's a waste of time to replay those 1000 records, because all the changes are overwritten by the final full page image.

To take advantage of that, perform WAL recovery in two phases. First, scan all the WAL and make note of the pages they modify. In the second phase, apply all the WAL, but skip changes that are overwritten by full-page images later.

**Comment by ololobus** [comment]
I thought about this topic a bit after your session on Unconference and tried to figure out cases, when this is most useful for vanilla Postgres. After a brief looking on FPW logic it seems that for a standalone Postgres, i.e. only crash recovery case, it is not that useful, since we are writing full-page images only once per page after each checkpoint / RedoRecPtr.

Yet, this should be useful for PITR, when we have an archive and Postgres may need to apply a long chain of WAL records. In this case "First, scan all the WAL and make note of the pages they modify." may be hard and time-consuming, since required WAL size could be arbitrary large, while archive storage could be rather slow and require network operations and/or retries (e.g. like S3). Also, normally Postgres should remove / rotate unused WAL segments (even during recovery, I guess, although not checked yet), while here we need to keep all the required WAL locally to do this first pass.

Maybe there should be some look-ahead threshold here? For example, there is a parallel process, that does WAL prefetch AND collects this pages information. If there is no FPW for the given page on the horizon, then recovery process still applies all records one by one.

Probably this look-ahead threshold could be figured out from the checkpointing configuration, so we will do some kind of jumps from one checkpoint to another. (I expect for some reason that FPWs density is higher after checkpoint).

P.S. Not a suggestion, just trying to clarify things for myself.

**Comment by hlinnaka** [comment]
> I thought about this topic a bit after your session on Unconference and tried to figure out cases, when this is most useful for vanilla Postgres. After a brief looking on FPW logic it seems that for a standalone Postgres, i.e. only crash recovery case, it is not that useful, since we are writing full-page images only once per page after each checkpoint / RedoRecPtr.

Yeah. Although if you crash while a checkpoint is in progress, then you could still skip WAL for pages for which you already created a FPW after the checkpoint has started. And there are a few other cases where it would help. If a relation is dropped or truncated by vacuum, can skip replaying the WAL before the drop/truncation.  But I agree it doesn't seem that useful.

However, we could make it a lot more efficient by e.g. writing an additional full-page image every 1000 updates to a page. That would have a small impact on the running server, but it could reduce crash recovery time a lot.

> Yet, this should be useful for PITR, when we have an archive and Postgres may need to apply a long chain of WAL records. In this case "First, scan all the WAL and make note of the pages they modify." may be hard and time-consuming, since required WAL size could be arbitrary large, while archive storage could be rather slow and require network operations and/or retries (e.g. like S3). Also, normally Postgres should remove / rotate unused WAL segments (even during recovery, I guess, although not checked yet), while here we need to keep all the required WAL locally to do this first pass.
> 
> Maybe there should be some look-ahead threshold here? For example, there is a parallel process, that does WAL prefetch AND collects this pages information. If there is no FPW for the given page on the horizon, then recovery process still applies all records one by one.

Yeah, makes sense.

> Probably this look-ahead threshold could be figured out from the checkpointing configuration, so we will do some kind of jumps from one checkpoint to another. (I expect for some reason that FPWs density is higher after checkpoint).
> 
> P.S. Not a suggestion, just trying to clarify things for myself.

Would you like to write a patch for this?

**Comment by ololobus** [comment]
> Yeah. Although if you crash while a checkpoint is in progress, then you could still skip WAL for pages for which you already created a FPW after the checkpoint has started. And there are a few other cases where it would help. If a relation is dropped or truncated by vacuum, can skip replaying the WAL before the drop/truncation. But I agree it doesn't seem that useful.

Oh, I see, thanks.

> Would you like to write a patch for this?

That would be interesting, although quite challenging for me in the same time, as I currently have more questions than answers about how to design this thing:

- What kind of structure in shared memory we should use to track information about pages? HashMap (blockno, relfilenode, etc) -> LSN of the last discovered FPW for this page?
- It seems that we have to use DSM here, since this structure should be able to grow.
- With a single look-ahead process this appears to be single-reader single-writer problem, so it seems reasonable to just use atomics, but should we limit ourselves to only one process?
- Otherwise we need to use locks, I guess. At a first look `dynahash` supports locking and even partitioned, however, its shared memory implementation cannot grow on the fly.

BTW, just remembered that there was a patch from PostgresPro guys about WAL prefetch workers [1]. Although David Steele and Andrey Borodin proposed that it would be better to delegate this work to 3rd-party utility by updating restore_command syntax to be able to specify prefetch size.

[1] https://commitfest.postgresql.org/32/2935/

**Comment by hlinnaka** [comment]
On 11 June 2021 23:09:33 EEST, Alexey Kondratov ***@***.***> wrote:
>- What kind of structure in shared memory we should use to track information about pages? HashMap (blockno, relfilenode, etc) -> LSN of the last discovered FPW for this page?

Yeah, a hash table fit the bill.

>- It seems that we have to use DSM here, since this structure should be able to grow.

Or you start replaying records to free up space, if the hash table fills up.

>- With a single look-ahead process this appears to be single-reader single-writer problem, so it seems reasonable to just use atomics, but should we limit ourselves to only one process?
>- Otherwise we need to use locks, I guess. At a first look `dynahash` supports locking and even partitioned, however, its shared memory implementation cannot grow on the fly.
>
>BTW, just remembered that there was a patch from PostgresPro guys about WAL prefetch workers [1]. Although David Steele and Andrey Borodin proposed that it would be better to delegate this work to 3rd-party utility by updating restore_command syntax to be able to specify prefetch size.

Thomas Munro proposed doing it all in the startup process: https://www.postgresql.org/message-id/CA%2BhUKGJ4VJN8ttxScUFM8dOKX0BrBiboo5uz1cq%3DAovOddfHpA%40mail.gmail.com. It's a long thread and I haven't been following it so I don't know what the current status is.

One open question I have is whether the prefetching should copy all the WAL records into the hash table, or just remember the latest FPW LSN of each page. If you keep the actual records, then you don't need to read the WAL again. And if it fills up, you can easily pick some old records from the hash table and apply them, to make space. OTOH holding the records will take a lot more memory. I'm leaning towards keeping whole records, it seems simpler, but not sure..

- Heikki
