### ISSUE TITLE
"Could not remove old wal-redo-datadir: Directory not empty"

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2400]
Got a test failure in the CI:
https://github.com/neondatabase/neon/runs/8213964163?check_suite_focus=true
```
2022-09-06T18:41:15.448031Z ERROR handle_pagerequests{tenant_id=6edc3486d5c6302aad07d93f14f2d6cf timeline_id=01ae5a3dd93c58a45af94713ba32f37c}:handle_get_page_at_lsn_request{self=PageServerHandler { conf: PageServerConf { id: NodeId(1), listen_pg_addr: "localhost:15131", listen_http_addr: "localhost:15132", wait_lsn_timeout: 60s, wal_redo_timeout: 60s, superuser: "cloud_admin", page_cache_size: 8192, max_file_descriptors: 100, workdir: "/tmp/test_output/test_pageserver_recovery/repo", pg_distrib_dir: "/tmp/neon/pg_install/v14", auth_type: Trust, auth_validation_public_key_path: None, remote_storage_config: None, profiling: Disabled, default_tenant_conf: TenantConf { checkpoint_distance: 1048576, checkpoint_timeout: 600s, compaction_target_size: 134217728, compaction_period: 1s, compaction_threshold: 10, gc_horizon: 67108864, gc_period: 100s, image_creation_threshold: 3, pitr_interval: 2592000s, walreceiver_connect_timeout: 2s, lagging_wal_timeout: 3s, max_lsn_wal_lag: 10485760 }, broker_etcd_prefix: "neon", broker_endpoints: [Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(15001), path: "/", query: None, fragment: None }] }, auth: None, claims: None } rel=1663/12972/2663 blkno=1 req_lsn=0/16AE7D8}: could not remove old wal-redo-datadir: Directory not empty (os error 39)
```
This was on a PR with significant changes to the pageserver code, although nothing related to the WAL redo process so I believe this is a pre-existing issue.

The test kills the pageserver abruptly, and then restarts it. My theory is that the when the pageserver process dies, WAL redo process keeps running. We then clear the old `wal-redo-datadir`, but because the process is still running, we fail to remove some files in it. Or the WAL redo process recreates some files in it, although that should not be possible after it has dropped privileges with seccomp().

Need to investigate. Maybe add some sleeps into the WAL redo process, to see if that makes it reproduce.

One way to fix this could be to always create the `wal-redo-datadir` with a new temporary name, so that if the old process is still running, it won't interfere with creating new process. But before we reach out to that fix, it would be nice to know what exactly happened.

**Comment by koivunej** [comment]
[Noted this](https://github.com/neondatabase/neon/pull/2875#issuecomment-1329408361) in the #2875 while trying to reproduce a CI crash yesterday in a loop:

```bash
while true; do RUST_BACKTRACE=full nice -20 ./scripts/pytest test_runner/regress/test_gc_aggressive.py && rm -rf test_output || break; done
```

`rm -rf test_output` would fail when racing with the walredo `initdb`.

In my test case I hit the immediate [`std::process::exit(111)`](https://github.com/neondatabase/neon/blob/52166799bd4a7743253ba3ccddbba3986f4e5fe9/pageserver/src/bin/pageserver.rs#L357) for sure (because postgres died or failed to start), but I think similar result can happen through the [shutdown_pageserver](https://github.com/neondatabase/neon/blob/ae53dc3326715159988ca7cfda57d4b84fb9319c/pageserver/src/lib.rs#L86).

I suspect the problem in general is that `std::process::exit` is called instead of just exiting through the main normally after shutting down everything, including tokio runtimes.

**Comment by knizhnik** [comment]
I do not think that `std::process::exit` is somehow related.
Actually returning from main is the same as calling `exit`.
The problem is that we are not waiting termination of walredo process.
It is connected with pageserver by pipe. If process at one end of the pipe is terminated (pageservere)
then sooner or later process at another end of the pipe will get EPIPE and and also finishes.
But there is no any warranty when it happen. If walredo process is busy at this moment with something (reconstructing page) and not reading or writing something to the pipe, then it can leave arbitrary long time after termination of pageserver (doesn't matter how it is performed).

I see the following solutions:
1. Close the pipe and wait until walredo proess is actually terminated: et it's exit stats.
2. Insert small delay in test (just sleep) before restarting pageserver.
3. Generate unique directory for walredo

2) seems to be the most easiest workround, but it is not reliable.
1) is the most difficult to implement and ... actually it useless code, because we rarely need to restart pageserver except for testing.
I prefer 3) because there is other problem which I have faced when trying to implement buffered walredo.
We are actually launching pageserver twice: first time to bootstrap and second - for normal work.
Actually I do not remember why it is stictly needed and why bootstraping can not be done during first launch of the process.
But pageserver immediately spawn walredo process, the two pginit will conflict for the same PGDATA directory.
Right now we are spawning walredo process lazily (on demand) and that it is why it is not started during bootstrap. But it requires mutex lock at each redo operation.It can be avoidded if we spawn walrdo process from WalRedoManager constructor.

**Comment by hlinnaka** [comment]
Happened again in https://neon-github-public-dev.s3.amazonaws.com/reports/main/release/3832843209/index.html#suites/21390de3eb46b5cc434a72f68ea23b6b/eab709f50e762d40/.

**Comment by SomeoneToIgnore** [comment]
Have added more debug info in https://github.com/neondatabase/neon/pull/3254 ,but so far no good luck catching this particular error.

**Comment by shanyp** [comment]
#3703  removed the directory
