### ISSUE TITLE
Include layer file sizes in `index_part.json`

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2456]
Once we implement on-demand download of layer files, the "physical size" of a project that we report will no longer include remote layers that are not present in the pageserver. But the console would need to get the total size of the project on S3. 

Include the size of each layer file in the `index.json` file, so that we know the size of remote layers in the pageserver. Must be careful to make the change in a backwards-compatible fashion, so that the new pageserver version can still read old `index_part.json` files that are missing the layer sizes.

**Comment by SomeoneToIgnore** [comment]
If I understood the proposal right, we're adding a new file? Could name it `timeline.json`, for better clarity.
Might also extend the name with version number, or similar metadata.

We can consider adding two more things into the updated json file:
* versioning info, that's currently missing (metadata is embedded inside as bytes, so that version has to be taken into account or the approach reworked)
* file checksums, and now use the values, compatible with that we have in AWS S3

**Comment by hlinnaka** [comment]
> If I understood the proposal right, we're adding a new file?

I was thinking of just adding new fields to the the old file.

>  Could name it `timeline.json`, for better clarity. 

Sure, we could rename it. Just have to deal with backwards-compatibility.

> Might also extend the name with version number, or similar metadata.
>
> We can consider adding two more things into the updated json file:
> 
>     * versioning info, that's currently missing (metadata is embedded inside as bytes, so that version has to be taken into account or the approach reworked)
> 
>     * file checksums (at least, as a placeholder to do the format changes once) to later fill with the values, compatible with what we have in AWS S3

+1

**Comment by koivunej** [comment]
> versioning info, that's currently missing (metadata is embedded inside as bytes, so that version has to be taken into account or the approach reworked)

During the PR I failed to consider this at all and was thinking the two were allowed to evolve separately. If they need to be in sync, the PR can be reworked to receive the version tag from the `TimelineMetadataHeader` instead of `index_json.json` "internal tagging", requiring only `.metadata` property to be present in all of the future versions.

> file checksums (at least, as a placeholder to do the format changes once) to later fill with the values, compatible with what we have in AWS S3)

I understand that this was supposed to be SHA-256 but as far as I can see, there's none at the moment, looking at `libs/remote_storage`. This is probably because trailer headers are not fully supported for http/1.1 nor does rusoto support sending them?

**Comment by koivunej** [comment]
Oops, reopening as this was the only issue with checksums.

**Comment by hlinnaka** [comment]
> Oops, reopening as this was the only issue with checksums.

Can you create a new issue for that, please? This one is complete, we have the sizes in 'index_part.json` now, right?
