### ISSUE TITLE
walproposer hangs if single safekeepers hangs

### ISSUE THREAD

**Issue by petuhovskiy** [neondatabase/neon#2569]
## Steps to reproduce

Run a single safekeeper that accepts new connections and accepts new messages, but doesn't reply with any messages. Other 2 safekeepers should be healthy. Run `postgres --sync-safekeepers` and it will stuck.

For example, this happened in https://github.com/neondatabase/cloud/issues/2426 because we had a deadlock (#2566) and timelines became locked when they tried to persist something to disk. This made safekeeper read new messages without replying back.

## Expected result

walproposer requires only 2 working safekeepers to finish `--sync-safekeepers`. It also should drop connection to safekeeper if it doesn't receive new messages for some time (~5 seconds).

## Actual result

`postgres --sync-safekeepers` doesn't exit

**Comment by andresrsanchez** [comment]
Hi @petuhovskiy, so i did a little test on my computer trying to replicate that scenario:

- Manually provoke a deadlock on [PhysicalStorage](https://github.com/neondatabase/neon/blob/main/safekeeper/src/wal_storage.rs#L270) to avoid writing to disk in only one safekeeper. 
- Modify [test_sync_safekeepers](https://github.com/neondatabase/neon/blob/main/test_runner/regress/test_wal_acceptor.py#L688) to do `append_logical_message` in background just to avoid the exception because of the previous deadlock.
- Run the test and i see that hangs on `sync_safekeepers`, great!
- With gdb i can check that one safekeeper is stuck in `epoll_wait` coming from [WaitEventSetWait](https://github.com/neondatabase/neon/blob/main/pgxn/neon/walproposer.c#L344) with `SS_HANDSHAKE_RECV` state, and this state cannot move forward.

So at the end i modified `WalProposerPoll`:
```
for (int i = 0; i < n_safekeepers; i++)
{
	Safekeeper *sk = &safekeeper[i];

	if ((sk->state == SS_CONNECTING_WRITE ||
		 sk->state == SS_CONNECTING_READ ||
                  sk->state == SS_HANDSHAKE_RECV ) && /* <------------------ I added this line */
		TimestampDifferenceExceeds(sk->startedConnAt, now, wal_acceptor_connect_timeout))
	{
		elog(WARNING, "failed to connect to node '%s:%s': exceeded connection timeout %dms",  sk->host, sk->port, wal_acceptor_connect_timeout);
		ShutdownConnection(sk);
	}
}
```
And now the conn gets dropped and the test does not get stuck.

So i am a new in this repo and is possible that everything i said i'm wrong, if so, excuse me. Let me know what you think please, thanks!

**Comment by petuhovskiy** [comment]
Hi @andresrsanchez! You got the idea right. Your fix works if safekeeper is stuck in `SS_HANDSHAKE_RECV` state and fixes the original issue. But I'd try to create a general fix, which will also work if safekeeper will be stuck in any other state.

The idea for a general fix is to track timestamp of the last received message from the safekeeper. If we are connected to a safekeeper from which we have not received a message in the last 5 seconds, then we can disconnect from it by timeout. It should work because we have a logic to send a message every second between compute and safekeeper.

It's actually not very different from your patch, you can try to open a PR with the proposed general fix.



P.S. We also have another issue here:
> walproposer requires only 2 working safekeepers to finish --sync-safekeepers.

In theory, we got 2/3 responses from the safekeepers and we could finish the sync immediately – then we wouldn't have hanging sync. But right now we are waiting for all alive safekeepers and this issue is a bit harder to fix properly, we should come back to it later.

**Comment by arssher** [comment]
done
