### ISSUE TITLE
report the history size from the pageserver to prometheus

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#2580]
report the history size from the pageserver:
1. WAL size
2. the amount of days it's configured for

this should be reported per tenant & timeline
report to prometheus, separately from the current size metrics

**Comment by hlinnaka** [comment]
The goal is that we will have a new per-tenant metric, displayed in the console (initially maybe just in the Admin panel): "current pricing size". That's the output of the pricing model, which is based on the logical db sizes and the history sizes of the timelines.

For starters, if we could just extract number for all the existing tenants, and export them e.g. to a spreadsheet, that would be great. The console changes can be done later.
To calculate that that, we'll need the gather the inputs for the pricing model. I think that includes:

* `last_record_lsn` value of each branch
* The branch points of each branch. That is, the ancestor_timeline_id and ancestor_lsn value of each branch.
* user-configurable retention period, in gigabytes or days (it could be different for each branch, too, but I think we can assume a single value for now)
* last LSN that needs to be retained, on each branch. If retention period is given as a size, it's simply last_record_lsn - retention_period. If it's given in days, then it's get_lsn_by_timestamp(now - retention_period) . Let's call this value `last_retain_lsn` * logical size of the database, at different LSNs:
  * at last_retain_lsn of each branch
  * at each branch point

If you can gather all that data for a tenant, you can feed them into the pricing model, and get the "pricing size" as output. That gives you a snapshot of the "pricing size" that you'd pay for. In order to actually do billing, we'll need to repeat that calculation at some interval, e.g. once a minute.

**Comment by koivunej** [comment]
In initial implementation #2714 this was the original direction, but concerns about performance and configurability dropped it in favor of just getting something done in staging, maybe production, with the request api.

Last we discussed that two values dimensions might be needed (unsure if they related to the metrics usage or just planned request api usage on console):
- one with the default retention period (max, as of #2817)
- one with the retention period of zero

Noted the non-incremental nature of logical size calculations, @hlinnaka didn't consider it to be a blocker for going to production with the implementation (after latest PRs). We just need configurability to turn off/on the background task and metric calculation via configuration (`PUT /v1/tenant/{tenant_id}/config`) like was originally planned. This should be added to some on-call instructions, so that it becomes one of the earliest people will reach with too high cpu usage. It must be noted that the config update will then have to cancel any currently running size calculation (which goes on seemingly forever, or is hogging all of the cache).

Related to configurability, rollout strategy needs to be thought of. In production, perhaps this could be enabled for tenants in waves.
