### ISSUE TITLE
Defunct wal-redo processes

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#2761]
Currently on prod:

```
$ ps wuax | grep postgres | grep defunct | wc -l
7209
```

**Comment by problame** [comment]
Looking into this.

**Comment by problame** [comment]
My best lead on this is the following scenario:

1. Create tenant struct
2. Create timeline struct
3. Do one WAL redo, so that the process gets spawned
4. drop timeline struct
5. drop tenant struct

Since we each tenant's `PostgresRedoProcess` in an Arc, step 5 will call `Drop::drop` on the `PostgresRedoProcess`, which does the following:
6. drop in-memory struct `PostgresRedoProcess::child: Child` (dropping a `Child` doesn't kill / wait on anything)
7. drop `PostgresRedoProcess::stdin ChildStin`,  and all the other FDs. Since they're just FDs, dropping them will cause a `close()` call to the pipe FDs.

Step 7 will cause a SIGPIPE / EPIPE in the wal-redo process. It will exit.

But the pageserver doesn't `wait()` for the wal-redo process. In fact, we've already dropped our handle to it, i.e.,  `PostgresRedoProcess::child`.
So we get a zombie process.

## Validating the hypothesis

TBD. Do we need to? Seems pretty obvious to me.

## Fixing the problem

### Approach 1 (quick fix)

We can add a `Drop` impl to `PostgresRedoProcess` that will kill & wait the child process.
The problem with that is that `Drop` is supposed to be infallible.
But wait & kill can fail.
And further, it can take a good amount of time if the system is really busy.
It'll probably work well with how we use `PostgresRedoProcess` today.
But there might be problems in the future.

### Approach 2 (more robust, long-term maintainable)

The alternative I have in mind: **Handle pattern**.
The idea is that we have a separate OS thread per redo process.
Clients of the redo process go through a Handle object which they use to request wal redo from the redo thread.
Redo thread takes care of spawning communicate with the redo thread.
 that takes care of properly killing it.

Usage:

```
# create tenant
let handle = PostgresRedoProcess::new();
Tenant {
  redo_process: handle,
}

# create timeline
Timeline {
  redo_process: tenant.redo_process.clone()
}

# use handle in timeline code
timeline.redo_process.apply_wal_records()
```

Implementation sketch:

```
fn PostgresRedoProcess::new():

  sender, receiver = make mpsc channel

  process_manager_thread = thread::spawn(|| {
    child_process = None
    loop {
      request = match receiver.recv() {
        Ok(request) => request,
        Err(all sender are gone) => {
            child_process.kill();
            return;
        }
        Err(x) => log and continue,
      };

      if child is Some and has exited:
        log error about unexpected exit
        child = None
      if child.is_none():
        child = spawn child process

      res = child_process.apply_wal_records_impl # what the current function does

      request.response_sender.send(res)
    }  # end loop
  }); # end thread closure

  # the thread will exit when the child exits or if the last Handle is dropped
  drop(process_manager_thread);

  return Handle {
    sender,
  }

fn Handle::clone(self) { Handle { sender: self.sender.clone() }}

fn Handle::apply_wal_records(args...):
  response_sender, response_receiver = channel()
  self.sender.send(Request { response_sender, args... })
  response_receiver.recv()
```

If we think threads are too heavyweight, I guess I could have a look at ways to do it in async Rust.

---

Opinions, @hlinnaka ?  (he wrote the current implementation)

**Comment by hlinnaka** [comment]
Some things to consider:

- We're just discussing how we could speed up the communication between pageserver and the walredo process. See https://github.com/neondatabase/neon/issues/1339. This has been in the backburner, but Konstantin's recent testing shows that it's a bottleneck in our sequential scan speed so we will need to address it soon. So we need to be careful with any overhead here, this is very latency sensitive codepath. `mspc` is fast, and there are probably even faster alternatives in tokio or parking_lot so maybe it's OK, but I'm not sure.

- Sooner or later, we'll need more to have than 1 wal redo process per tenant. See https://github.com/neondatabase/neon/issues/807. We've been putting off doing that too, but I think soon we'll need to. We' should probably also have a timeout or something, to kill WAL redo processes that are not being actively used, to keep the number of processes in check.

- This is somewhat similar to the problems we've been having with dropping Tenants and Timelines, see https://github.com/neondatabase/neon/issues/2705 and the RFC. Maybe there's a common approach. @alexstanovoy actually suggested the Actor pattern for that, which is very similar to what you're proposing with the handler thread above. I was pretty skeptical of that for Tenant/Timeline, but it makes more sense for the WAL redo process case, when there is naturally one process to manage. However, if we need to manage a pool of processes, then it gets complicated again.

- Yeah, should be a tokio Task rather than thread.

**Comment by hlinnaka** [comment]
The rust `Child` wait/kill functions are strange. They both take `&mut self` as the argument, so it's impossible to have one thread/task waiting for it to finish, and kill it from another thread/task. Weird limitation, knowing that the libc waitpid and kill just take a 'pid'.

**Comment by problame** [comment]
## Approach 3: `Undroppable` type

I guess what we want in the short term is a compile error whenever we forget to call fallible cleanup operations.

I found this hack which gives us almost that:
https://www.reddit.com/r/rust/comments/my3ipa/comment/gw0g636/?utm_source=share&utm_medium=web2x&context=3

Basically the idea is that it introduces a marker type whose `Drop` implementation will refer to a non-existent symbol.
To avoid a linker error, the `Drop` implementation must not be present in the compiled binary.

So, the recipe is like:
1. Add the marker type as a member of our undroppable struct, e.g., `PostgresRedoProcess::_undroppable: Undroppable`
2. In our fallible cleanup operation (`PostgresRedoProcess::kill`) 
2.1. consume `self` & destructure it
2.2. `std::mem::forget` the marker type value. That will cause the compiler to omit the `Undroppable::drop()` call on the marker type value, thereby avoiding the linker error.

**Comment by problame** [comment]
> at the differences at the offsite to the current implementation

Offsite? Please update your comment then hide this one.

**Comment by problame** [comment]
The change #2769 that adds more logging got deployed.

Analyzing logs on one of the affected pageserver hosts:

```
admin@zenith-us-stage-ps-4:~$ journalctl --since 08:00 --until 09:00 -u pageserver  --no-pager | grep "dropping PostgresRedoProcess that wasn't killed, likely causing defunct postgres process" | perl -n -e '/pid=(\d+)/ && print $1 . "\n" ' | sort > /tmp/candidates.txt
```
admin@zenith-us-stage-ps-4:~$ ps -e -o pid,stime,args | grep postgres | grep defunct | grep ' 08:' |awk '{print $1}' | sort > /tmp/defunct.txt
admin@zenith-us-stage-ps-4:~$ diff -u /tmp/defunct.txt /tmp/candidates.txt 
admin@zenith-us-stage-ps-4:~$ echo $?
0
admin@zenith-us-stage-ps-4:~$ wc -l /tmp/defunct.txt 
250 /tmp/defunct.txt
```

What this means: all of the 250 defunct postgres processes that were started between 08:00 to 09:00 were caused by the problem 
outlined [above](https://github.com/neondatabase/neon/issues/2761#issuecomment-1305479967).

I'm optimistic that we have found the root cause.
Moving on to fixing it in #2776 .
