### ISSUE TITLE
test_get_tenant_size_with_multiple_branches is flaky: tenant size mismatch

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#2962]
Test failure in CI:

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-2960/release/3578062809/index.html#suites/d70040d097c5c7c438e421e0416d69ce/7c9d794380df2ac4/

```
test_runner/regress/test_tenant_size.py:216: in test_get_tenant_size_with_multiple_branches
    assert size_after_second_branch == size_after_continuing_on_main
E   assert 26849176 == 26840904
E     +26849176
E     -26840904
```

The test assumes that the tenant size of a tenant doesn't change when you create a branch. However, there are Postgres instances running at the same time, and they could perform autovacuum or checkpoints at any time, which generates some WAL, which gets digested in the pageserver and increases the tenant size.

**Comment by koivunej** [comment]
Aah this is very interesting, cc: #2809

**Comment by yeputons** [comment]
Another one: https://github.com/neondatabase/neon/actions/runs/3717279273/jobs/6305177384

**Comment by lubennikovaav** [comment]
And one more.

https://neon-github-public-dev.s3.amazonaws.com/reports/release/release/3940332065/index.html#suites/d70040d097c5c7c438e421e0416d69ce/b8c447400602163/

**Comment by koivunej** [comment]
This one still is a problem... The defaulting of pg15 aside, what could be the reasons this happens? Relevant lines: https://github.com/neondatabase/neon/blob/9d3992ef48bb2904240ab27c402654f0f7528908/test_runner/regress/test_tenant_size.py#L208-L216

Collecting the additional asserts from the three cases above:

- `assert 26849176 == 26840904` ([issue desc](https://github.com/neondatabase/neon/issues/2962#issue-1468825453))
- `assert 26849176 == 26824360` (https://github.com/neondatabase/neon/issues/2962#issuecomment-1355974171)
- `assert 26840904 == 26824360` (https://github.com/neondatabase/neon/issues/2962#issuecomment-1385585111)

Interesting that we find the 26840904 on both sides of the assertion. In the order of apperiance:

- 26849176, aligned
- 26840904, aligned
- 26824360, aligned

What other than aligning could happen while branching but before a postgres has been started on that branch? Perhaps this needs to be inspected by storing of the model inputs from the relevant responses (line 209, line 215), and dumping wal between the delta assuming there is such and assuming this hasn't already been done? 

Another idea is that we get there is a record of the transaction being placed on the WAL after the line 208 (`wait_for_last_flush_lsn(env, main_pg, tenant_id, main_timeline_id)`) completes, as in calling that function will always generate more WAL (because it runs in an autocommit transaction)? This would require that these records are flushed lazily so this doesn't always get flushed by postgres before we do the second query (line 215)?

**Comment by koivunej** [comment]
Quite similar in https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3558/release/4121897774/index.html#suites/d70040d097c5c7c438e421e0416d69ce/7fa59139f79f5f2c/

**Comment by jcsp** [comment]
A recent failure of this test: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5207/6157084684/index.html#suites/d70040d097c5c7c438e421e0416d69ce/b1febc6dd89fed6c

```
test_runner/regress/test_tenant_size.py:576: in test_get_tenant_size_with_multiple_branches
    assert size_after_first_branch == size_at_branch
E   assert 25829376 == 25821184
```
