### ISSUE TITLE
Timeline X/Y was cancelled and cannot be used anymore

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3004]
## Steps to reproduce

Found in sk logs

## Expected result

No error in logs

## Actual result

```
Dec 04 11:58:21 safekeeper-1.us-east-2.aws.neon.build safekeeper[1360899]: 2022-12-04T11:58:21.550310Z ERROR {tid=50}:WAL acceptor{timeline=daa3f503e63abff68a4011f989fd75f0}: failed to unregister compute connection: Timeline ccec8f9b145737b93a4866903b6a582a/daa3f503e63abff68a4011f989fd75f0 was cancelled and cannot be used anymore
Dec 04 11:58:21 safekeeper-1.us-east-2.aws.neon.build safekeeper[1360899]: 2022-12-04T11:58:21.550339Z ERROR {tid=50}: query handler for 'START_WAL_PUSH' failed: Failed to process query for timeline daa3f503e63abff68a4011f989fd75f0
Dec 04 11:58:21 safekeeper-1.us-east-2.aws.neon.build safekeeper[1360899]: Caused by:
Dec 04 11:58:21 safekeeper-1.us-east-2.aws.neon.build safekeeper[1360899]:     Timeline ccec8f9b145737b93a4866903b6a582a/daa3f503e63abff68a4011f989fd75f0 was cancelled and cannot be used anymore
```

## Environment

New staging 

## Logs, links
-

**Comment by petuhovskiy** [comment]
This error means that we stopped sk timeline and all background tasks associated with this timeline should be eventually canceled. Right now, that happens only on timeline deletion because we want to shut down all background tasks after timeline was deleted. This log is quite useful because it shows the real reason why this particular task/connection was stopped and it also cannot happen more than `O(1)` times for a single timeline.

So, I don't know if there is any genuine issue here that should be fixed and what the fix should look like.

**Comment by LizardWizzard** [comment]
During normal operation there shouldnt be any ERROR messages in logs. So if this is normal lets change the log level to info or debug.

**Comment by petuhovskiy** [comment]
postgres_backend logs were reworked in #3759, but I still see similar logs:

```
2023-03-10T13:29:53.533731Z ERROR {cid=3329}:WAL receiver{ttid=X/Y}: terminated: Other(WAL acceptor
Caused by:
    Timeline X/Y was cancelled and cannot be used anymore
```

Need to take a closer look and probably adjust logs a bit more.

**Comment by petuhovskiy** [comment]
Should be better now, closing
