### ISSUE TITLE
Create a timeline subcommand to print its walreceiver state

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3115]
If walreceiver is stuck due to some reason, it might be simpler to send an HTTP GET query into pageserver management API instead of checking the logs for error messages.

New HTTP endpoint should return:
* all safekeepers whose messages were recently received from the broker
* Safekeepers' metadata, related to timeline: LSNs, last message time, etc.
* current active walreceiver connection metadata: SK id, time since connected, etc. or time since the last connection happened
* latest feedback message metadata? Latest lsn caught up to would be useful

**Comment by SomeoneToIgnore** [comment]
Might be more generic to expose the data via new metric(s).

**Comment by koivunej** [comment]
We've been happy with the summary of different safekeepers in the seqwait timeout error. But this would be easy to add for querying via http, maybe it could even be in the `timeline_detail` because you'll probably want to see `last_record_lsn` and other lsn's at the same time...?

With "summary of different safekeepers" I mean: https://github.com/neondatabase/neon/blob/a1d6b1a4af5252e1215571257d4e79e40d961c11/pageserver/src/tenant/timeline.rs#L641-L658

Added in #4090. So the same contents, not necessarily formatted to a string but as a json would be handy as `GET /v1/tenant/:tenant_id/timeline/:timeline_id/walreceiver` for example, or as part of `GET /v1/tenant/:tenant_id/timeline/:timeline_id`.

Adding a good_first_issue because this is mostly plumbing in what we already have, perhaps adding a bit of `serde::Serialize` and openapi changes. However the openapi changes can be opaque, as in this is something internal to help with the on-call operator, not something to be relied for stability.
