### ISSUE TITLE
potential data loss message in sk logs

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3146]
## Steps to reproduce
-

## Expected result

No such errors in logs

## Actual result
```
WARN load_timeline{timeline=44f55a8653f12e2a6e7d4b1356190123}: timeline 44f55a8653f12e2a6e7d4b1356190123 potential data loss: flush_lsn by find_end_of_wal is less than either commit_lsn or peer_horizon_lsn from control file
```
## Environment

stage

## Logs, links
-

**Comment by arssher** [comment]
This is related to deletion issue. Apparently all such projects are deleted; directory on sk has no WAL, but controlfile, which causes the WARN. cc @petuhovskiy

**Comment by arssher** [comment]
So, from [logs](https://neonprod.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bneon_service%3D%5C%22safekeeper%5C%22,%20neon_region%3D%5C%22us-east-2%5C%22,%20hostname%20%3D~%20%5C%22safekeeper-0.%2A%5C%22%7D%20%7C~%20%5C%22dc9bca6b825f9ab43870cb9b18b2b539%7C067b5ca2437a7bb4d6eb076030b29073%5C%22%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D) it is crystal clear compute is still alive when DELETE request comes in. Since we don't have explicit timeline creation, it creates new one. One more reason to have explicit creation...

On a related node, I also dislike`on_compute_disconnect` bailing out due to timeline being canceled. Unless we have proper shutdown, we should tli users shutdown normally to avoid messy shared state.

**Comment by arssher** [comment]
As a hack, until we have explicit creation, we can keep deleted timeline in hash (till next restart) to prevent these warns and empty directories accumulation. @petuhovskiy WDYT?

**Comment by petuhovskiy** [comment]
I think I even had a code in #2329 which kept deleted timelines in hash :) We definitely can do this, and I would also prefer to store info about deleted tenants on disk. 

I don't like explicit creation because it's hard to do it right, so let's start with keeping info about deleted timelines. cc @arssher

**Comment by arssher** [comment]
+1, and I'd propose to start with memory:
- it is straightforward to implement, and definitely enough to fix orphaned directories/scary warn issue
- it is straightforward to fix on overflow (just restart)

**Comment by LizardWizzard** [comment]
>  and I would also prefer to store info about deleted tenants on disk

Can you elaborate why? I dont get it why do we need to store some data for deleted tenants

**Comment by petuhovskiy** [comment]
> Can you elaborate why? I dont get it why do we need to store some data for deleted tenants

Short answer: to be safe and ensure that once deleted tenant won't reappear.

Long answer:

We have a distributed system with a lot of services talking to each other and many points of failure. The task here is to synchronize the state between all services, where the state is `Map<TenantTimelineId, Active | Deleted>`. We have a single source of truth for this state, it's stored in the console database.

We want to know the state in each service (console, safekeeper, pageserver, compute, etc.), because we want to allocate and free up resources for timelines accordingly. If we forget about the deleted state in safekeeper, we can accidentally recreate the timeline and fail to free up the resources (this exact issue). The most reliable way to ensure that we don't forget about the deleted state is to persist data to disk. That's why I proposed to keep info about deleted tenants on the disk.

Generally speaking, we may want to know not only whether the timeline is `Active` or `Deleted`, but also keep track of safekeepers and pageservers configuration (which safekeepers/pageservers are assigned to this timeline currently). Console (control-plane) is still a single source of truth of that info, and there are two good ways to access that state:
- Ask control-plane API every time to read the state (works best if control-plane is very reliable and HA)
- Store a local copy of the global state everywhere (requires effort to build a reliable pipeline to replicate state from control-plane database to all storage services)

There are also other ways, but in most of them we cannot guarantee that the state will converge, and we will not need to manually fix inconsistency artifacts that can happen because of restarts, partial unavailability, network issues, etc.

**Comment by LizardWizzard** [comment]
> we can accidentally recreate the timeline and fail to free up the resources (this exact issue)

It looks like the problem can be solved with explicit create action. In this case if someone reaches to you after and asks about deleted tenant it will be 404 or something like that

**Comment by arssher** [comment]
Fix with remembering deleted timelines until next restart was merged, this can be closed.
