### ISSUE TITLE
test_pageserver_recovery Failed to reconstruct the page error

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#3203]
Was caught in CI

https://neon-github-public-dev.s3.amazonaws.com/reports/pr-3187/debug/3759259147/index.html#categories/c0057473fc9ec8fb70876fd29a171ce8/7976d8667334d68f/

**Comment by knizhnik** [comment]
The source of problem seems to be here:
```
req_lsn=0/16A6660}:launch{tenant_id=0ccf87623b4eaa872af9f93e9e9f3a78 pg_version=14}: old temporary datadir /tmp/test_output/test_pageserver_recovery/repo/tenants/0ccf87623b4eaa872af9f93e9e9f3a78/wal-redo-datadir.___temp exists, removing
2022-12-22T16:23:07.429850Z ERROR 
```
Looks like we once again reproduce interleaving of two walredo processes?
How it is possible?
We are launching pageserver two times (still do no know why:) - first for bootstraping and second time - for actual work. Bootstrap cause initialization of tenants. But right now walredo process is started lazily on first reconstruct request. It is expected that it should never happen during bootstrap. And this is why walredo process is not spawned at first pageserver launch.
But looks like in your case something goes wrong. Or may be walredo interleaves with previous instance of walredo process which was  not terminated in time. It is hard to say. 

One of the worst thing with this bootstraping pageserver process is that is messages/errors are never logged (because logging system is not yet initialized).

**Comment by SomeoneToIgnore** [comment]
Should not be the case after https://github.com/neondatabase/neon/pull/3703
