### ISSUE TITLE
Fix pg_database_size() function

### ISSUE THREAD

**Issue by lubennikovaav** [neondatabase/neon#321]
This function still tries to read files from compute node's filesystem.
TODO: request database size from pageserver.

**Comment by stepashka** [comment]
@lubennikovaav , was this fixed already?

**Comment by stepashka** [comment]
we can still get the size of the cluster (with all its databases), lack of this only prevernts more granular infromation per database

**Comment by knizhnik** [comment]
I wonder what is the status of this task?
Do we still need to support it or pg_cluster_size() is enough?
@lubennikovaav suggested to extend smgr protocol with request to calculate db size.
It seems to be the only possible choice because alternative approach (just sum size of all db relations) seems to be not possible to implement, because we can not get list of relations of other databases, only if own database.
So it is quite easy to provide function:
```
CREATE FUNCTION pg_db_size()
RETURNS bigint AS $$
select sum(pg_relation_size(oid)) from pg_class where relkind='r'
$$ LANGUAGE SQL STRICT PARALLEL UNSAFE;
```

which returns (logical) size of the current database. It seems to be enough in 90% cases of pg_database_size() usage.
But if we want built-in pg_database_size() to provide relevant result, then we need to perform calculation at page server.
If it is needed, I can extend protocol and implement this method at pageserver.

**Comment by hlinnaka** [comment]
I think we should implement a more "proper" pg_database_size(). One difference with your 'pg_db_size' above is that it will not count relations that are being created by an in-progress database.

**Comment by hlinnaka** [comment]
On 17/02/2022 09:33, Konstantin Knizhnik wrote:
> Do you mean that it should take in account data inserted by not 
> committed transactions?
> Actually in case of zenith there are at least two different storage sizes:
> 
>  1. Logical size (number of blocks in all relations)
>  2. Physical size (real size of pageserver storage)
>     Right now there is no way for user to somehow get 2) and I am not
>     sure if it is actually needed (but it will be very interesting for
>     us to know ration between physical and logical size).
> 
> If we take in account in-progress updates then picture becomes even more 
> complicated.
> If we count calculate logical database size at pageserver side 
> (including all orphan relations)
> then we will see uncommitted changes, but not one which are not yet 
> processed by pageserver (somewhere in the middle of compute 
> WAL->safekeeper->pageserver pipeline). Maximal amount of such changes is 
> limited by back pressure parameters. If back pressure is switched off 
> the can be quite large.

I was thinking of 2, the size in the pageserver. True, it would not 
include WAL that is "in flight" and not processed by pageserver yet. I 
think that's OK. Or pg_database_size() could wait for the pageserver to 
catch up.

- Heikki

**Comment by stepashka** [comment]
below is what I'm getting for one of my clusters while this is not fixed

there's only one table holding data in this database.
based on the queries below it looks like the database size is smaller than the table it contains.

```
select pg_database_size('main'); 
pg_database_size
--
156450


select pg_table_size('timeseries'); 
pg_table_size
--
368640
```

**Comment by stepashka** [comment]
@lubennikovaav , is this fixed in PR that was just approved? :) https://github.com/zenithdb/zenith/pull/361
