### ISSUE TITLE
Epic: Configure PITR interval based size (additionally to time)

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#3297]
Now we store X days of WAL history, but have no limits on the size. We need to have a logic of "store X days of history but no more then Y gigabytes".

```[tasklist]
### Tasks
- [ ] What are the implications of allowing "unlimited" history size
```

**Comment by knizhnik** [comment]
It seems to be very user-unfriendly. So we actually give no clear criteria to the user on how long in the past he may expect to perform recovery.  What is Y? Size of WAL? Size of pageserver storage?
Assume that user starts migration with some bulk updates (altering table format). with this X/Y rule there will be no warranty that he can rollback this migration.
Also please notice that user is not always able to control WAL traffic: it can be produced not only by user transaction but also by autovaccum.

From my point of view it will be more honest to radically reduce PiTR interval (from days to let's say hours), so that it is not possible to produce too much WAL during this time. But do not enforce and WAL size limit.
More complex solution can be to reduce PiTR resolution, i.e. provide recovery to the arbitrary LSN during last hour, but then only to one hour timestamps. In this case we do not need to stored all WAL.

**Comment by kelvich** [comment]
> It seems to be very user-unfriendly. So we actually give no clear criteria to the user on how long in the past he may expect to perform recovery.

That is more to have a control over cost of free tier, e.g. 3 day but not more then 3GB. But I can see that useful in general context as well -- size is what user pays for, so having some configurable limit there is a nice way to avoid surprise check.

> What is Y? Size of WAL? Size of pageserver storage?

I was thinking of something like `current_lsn - oldest_historic_lsn`, so size of WAL.

> From my point of view it will be more honest to radically reduce PiTR interval (from days to let's say hours), so that it is not possible to produce too much WAL during this time. But do not enforce and WAL size limit.

If we are talking about the free tier even 3 hours can easily be ~500GB (pretty easy to write with 30mb/s * 3 * 60). So that is still quite high number in a worst case. So we can't have a _strict_ guarantee even on 3 hours. But there are plenty of cases when whole month will fit in that 3GB, e.g. think of some wordpress website that is changed from time to time, but overall database is 50MB or so. Would be nice to not to put such 3 hours restriction there.

As for the paid tier it makes sense to have an option to disable max history size limits and store everything.

> More complex solution can be to reduce PiTR resolution, i.e. provide recovery to the arbitrary LSN during last hour, but then only to one hour timestamps. In this case we do not need to stored all WAL.

Right, current PITR approach is good for small period (days) but may be too wasteful on year-like time scale. So probably we will end up with more classical non-PITR backups as well, where one can configure backups per month, per week and so on.

**Comment by stepashka** [comment]
started adding the use cases in the parent PReq:
https://github.com/neondatabase/neon_roadmap/issues/41

**Comment by jcsp** [comment]
We don't plan to do this.
