### ISSUE TITLE
>50 deltas without an image in between

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#3316]
We aim to have at most 3, but in practice we see 50-80 on some projects. This is a feedback loop, difficult reconstruction makes image generation more difficult, higher chance it's even more delayed next time. Not sure what the solution is.

_Originally posted by @bojanserafimov in https://github.com/neondatabase/neon/pull/2998#discussion_r1067549984_

**Comment by bojanserafimov** [comment]
Correction: excluding L0 layers, there are actually around 45-50 layers since the last image (not 50-80). Still a lot.

**Comment by shanyp** [comment]
@knizhnik is this still relevant with your recent change ?

**Comment by knizhnik** [comment]
> @knizhnik is this still relevant with your recent change ?

gc_feedback PR is not merged yet.
There are many different reasons which may cause such behavior:

1. Holes: sparse delta layers which case generation of  large number of image layers 
2. Holes between image layers 
3. "Stairs" - large number of partly overlapped delta layers which prevents generation of image layer because for the particuar key range umber of deltas is less than threshold (3)
4. Compaction and page reconstruction in the same task
1-2 are already merged, 3 is in progress, 4 - not addressed
