### ISSUE TITLE
Epic: allow to call gc via an api

### ISSUE THREAD

**Issue by LizardWizzard** [neondatabase/neon#3590]
## Motivation

Recently gc period has been [changed](https://github.com/neondatabase/neon/pull/3432) to 1 hour and in emergency when you're close to out of space situation on pageserver node you may want to decrease PITR horizon for some project and run gc immediately to free up some space. Thus the need for api

We have such an api, but it is accessible only with `testing` feature enabled

## DoD

gc api is available to use in binaries we deploy to prod

## Tasks
- [ ]

## Other related tasks and Epics
-

**Comment by koivunej** [comment]
This would probably lean on the currently open bug #2948 to actually gc anything, because gc will not create the image layers it needs to allow removal of layers. Without the over-reimaging, we should just early exit at https://github.com/neondatabase/neon/blob/f383b4d5401bd8ddb4e96a683af4d72496967d0a/pageserver/src/tenant/timeline.rs#L3307-L3316.

**Comment by LizardWizzard** [comment]
Yep, gc needs to work correctly in order for this api to be useful :)

**Comment by koivunej** [comment]
Note that the #2948 solutions don't discuss enabling gc to be used more like an adhoc tool, instead only the physical size explosion is dealt with. This manual gc would probably have to do something else to actually succeed, in order to do give expected results when called. Though this is also related to the "how much space is saved when gc after pitr_interval=0".

**Comment by shanyp** [comment]
Closed by #3639
