### ISSUE TITLE
introduce separate delete endpoint in pageserver so we delete files from s3

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3640]

**Comment by SomeoneToIgnore** [comment]
I would strongly consider safe deletions, since it's not clear from the issue which files are deleted via that endpoint.
In general, with https://github.com/neondatabase/neon/issues/2606 there will appear a service that, as part of its per-timeline checks, will ensure that S3 has no stale timeline data left on S3.
I think it could be safer to use such APIs in that place instead of pageserver.

**Comment by shanyp** [comment]
This was part off the original list of tasks in https://github.com/neondatabase/neon/issues/2427, if its not relevant please close it

**Comment by SomeoneToIgnore** [comment]
Given that S3 is considered our main storage, I am more comfortable with knowing that pageserver has no code to delete an arbitrary file from that storage.

I think, https://github.com/neondatabase/neon/issues/2427 is good to start with general discussions on how we delete things, since there are could be e.g. stalled timelines, deleted in the console — a pageserver would never be able to know about these and delete them, but something should.
Presumably, that something could GC things too: one of the ideas is https://github.com/neondatabase/neon/issues/2606#issuecomment-1431813066 but it needs quite an amount of work before it could be implemented.
