### ISSUE TITLE
Download of remote layers don't enforce timeouts

### ISSUE THREAD

**Issue by shanyp** [neondatabase/neon#3672]
Looking at https://github.com/neondatabase/neon/blob/6a9d1030a687d6c4ebd415f702441f09d679fab4/pageserver/src/tenant/remote_timeline_client/download.rs#L78

We reached a state that the operation was blocked (due to https://github.com/neondatabase/neon/issues/3657)
If we would have used a timeout for the copy operation, the exponential backoff for handling errors would have allow the system to break out from the dead lock state

**Comment by problame** [comment]
>  If we would have used a timeout for the copy operation, the exponential backoff for handling errors would have allow the system to break out from the dead lock state

Not sure how I feel about adding timeouts here.
The way I see it:

* Pro: a timeout here would have prevented the outage in staging
* Con: the timeout would have manifested in something like "whenever we restart the pageserver, there's this slew of timeout errors, but then it's fine". I think we would have de-prioritized such a symptom and wouldn't have spent the time to properly root cause this, which, IMO, was the right thing to do.

Regardless of pro & con: if we decide to add a timeout, it must not be on the copy operation as a whole, but the read & write operations invoked by `copy`.
I.e., not like this:

```
tokio::time::timeout(Duration::from_secs(30), tokio::io::copy(...))
```

because, if the download is a little slow, or the disk is a little slow, but is making progress, we'd still give up after 30 seconds, **waste all that work**, and likely retry the download shortly after, because _something_ clearly needs this layer file.

IDK if there is a `NoActivityPipe` type that we could interpose here.

**Comment by shanyp** [comment]
see my PR answer
WDYM by NoActivityPipe ?
