### ISSUE TITLE
Add S3 offloading mechanics to safekeepers

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#37]
Subj.

I'll use term wal_service for safekeer_proxy .

I suggest not try invent something complicated now and just put config param / option to safekeeper, that we were able to start one of them with --s3-offload option.

I imagine something following:
* each safekeeper has its own synced_lsn (recent wal synced to disk), s3_lsn (wal pushed to s3) both of that is reported back to proxy. s3_lsn is only reported by safekeeper with  --s3-offload flag.
* proxy sees majority_max(synced_lsn) and decides VCL and sees majority_max(s3_lsn) and decides trim_lsn. 
* WAL older trim_lsn can be deleted.

In this setup only one safekeeper will advance s3_lsn, but by reporting it to the wal_service it will affect trim_lsn, and allow his peer safekeepers to delete old WAL.

If safekeeper with --s3-offload will die, then other safekeepers will stop trimming WAL until one of them would be restarted with --s3-offload.

**Comment by kelvich** [comment]
s3 offloading in safekeeper was written and manually tested, but lacks any automated testing. We can rely on minio for local env and on docker image with minio for CI tests. @arssher

**Comment by mklgallegos** [comment]
Hi @arssher  it looks like this issue is assigned to you. When you have a chance can you provide an update on this? 

it would be helpful to know:

1. What is the exit criteria for this case? i.e. what work needs to be completed to satisfy this issue? Right now exit criteria seems kind of vague and would be helpful to specify what you think needs to be done in the v0.1 milestone for this issue.
2. work left to be done (a checklist of items would be helpful) 
3. any blockers?

**Comment by arssher** [comment]
The current state of things is the following. We have rather raw, basic implementation of WAL files offloading to s3 from safekeepers. Notably, it lacks synchronization between safekeepers, i.e. 1) who is responsible for the offloading and 2) broadcast of pushed LSN so that everyone can remove old WAL; also 3) tests.

Moreover, the whole idea is currently not as solid as it should as we might move WAL offloading to pageservers, see
https://github.com/zenithdb/rfcs/blob/storage_details/storage_details.md
So we should first decide this.

**Comment by antons-antons** [comment]
integration with remote storage https://github.com/neondatabase/neon/pull/1583
