### ISSUE TITLE
Ensure timeline is uploaded to the remote storage on creation, before returning 200

### ISSUE THREAD

**Issue by SomeoneToIgnore** [neondatabase/neon#3865]
https://github.com/neondatabase/neon/pull/3857#discussion_r1144410564

Now we create timeline local files, schedule a background upload job and return 200 to the console that invokes the creation.
Yet, if another pageserver would `attach` the tenant, it might miss the new timeline (root or branch) on the remote storage which potentially might cause issues.
If the original pageserver dies during the background upload job, that is even more likely to happen, yet in either case, console would consider the timeline alive and active due to 200 returned.

We need to change the approach and acknowledge the creation only after the sync is successful.

**Comment by koivunej** [comment]
If I understand correctly, the issue is that we only schedule and `index_part.json` upload for the new timeline but don't wait to complete that upload. The current `schedule_*` apis do not support awaiting for scheduled work to complete. Looking around to see how is this meant to be supported, perhaps with barrier?

**Comment by problame** [comment]
We have `wait_completion`

**Comment by hlinnaka** [comment]
I bumped into this in the tests I wrote for https://github.com/neondatabase/neon/pull/4170. I added a workaround in those tests, with a link to this issue. Once this is fixed, those workarounds can be removed.
