### ISSUE TITLE
Fix bulk upload of WAL

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#3957]
1. Cap the batches to advance backup_lsn & trim WAL earlier
2. Fix/adjust unstable offloader election in case of high throughput, if it is unstable.

- [X] update backup_lsn after every segment upload
- [x] use a task pool for parallel segment uploading
- [ ] slow down safekeepers if commit_lsn grows much faster than backup_lsn
- [ ] Out of space shouldn't prevent WAL deletion. Currently there is a deadlock: WAL is not deleted until backup_lsn in the control file is persisted, and control file update needs space. I guess WAL remover should look at in memory value of backup_lsn, and WAL offloader on attempt to offload locally non existing segment should check whether it is already present in s3.

https://neondb.slack.com/archives/C03H1K0PGKH/p1680711337200439

**Comment by petuhovskiy** [comment]
Latest experiments (https://neondb.slack.com/archives/C03H1K0PGKH/p1680792755591479) also show that WAL backup is slower than WAL generation:
- WAL gen. speed is ~138MB/s
- WAL backup speed is ~70MB/s

Not sure if this is due to bug or S3 is slow, but we should also fix this. I think we can try to upload in parallel, should be faster.

**Comment by arssher** [comment]
With parallel upload implemented we haven't seen these issues anymore. We might want to add one more kind of backpressure at some point, but let's do that separately, so closing the task.
