### ISSUE TITLE
cold starts: 16MB basebackup

### ISSUE THREAD

**Issue by bojanserafimov** [neondatabase/neon#4481]
related epic: https://github.com/neondatabase/cloud/issues/5315

We send a 16MB wal segment that maybe could be created client-side instead:
https://github.com/neondatabase/neon/blob/4936ab6842e30cc2196556b25fc322c9b303ee4b/libs/postgres_ffi/src/xlog_utils.rs#L374

**Comment by bojanserafimov** [comment]
If there are no better proposals, I will try to avoid sending pg_wal by instead including the inputs to `generate_wal_segment` into the basebackup, and calling the function client-side to create the segment.

I tried just not sending a wal segment, but that didn't work because postgres created it by itself, and the same amount of high network IO happened (not sure if the pg_wal file was downloaded, or uploaded by compute node).

**Comment by knizhnik** [comment]
Why don't we compress basbackup?
Although `tokio_tar` doesn't support compression, `GzEncoder`/`GzDecoder` can be added on top of it.

**Comment by bojanserafimov** [comment]
I tried compression with `flate2` crate's `GzEncoder`, and it got the size down to 20KB, which is even better than 60KB (which would be the original uncompressed size, minus pg_wal).

A small downside is that GzEncoder is not async. I tried the `async-compression` crate but it didn't work. It couldn't decode it's own output (assuming I used it right).

**Comment by knizhnik** [comment]
Well, it is strange that async-compression doesn't work.
According to the error it seems to be some error in your code - will try to review it.
There is also xz2 crate https://docs.rs/xz2/latest/xz2/
which support async model.

Actually I got one more prove (for myself) that async is awful model and the fact that it spreads across almost all programming languages makes me very confused: we eliminate stack for the price of doubling class library + makes debugging and profiling almost impossible. Awful.

**Comment by knizhnik** [comment]
Looks like async-compression really doesn't work.
At least in combination with tokio_tar.
Performing compression in memory helps.

**Comment by bojanserafimov** [comment]
> Performing compression in memory helps.

Even in memory I couldn't get it to work. I bet there's some missing flush somewhere

**Comment by knizhnik** [comment]
> > Performing compression in memory helps.
> 
> Even in memory I couldn't get it to work. I bet there's some missing flush somewhere

Hmmm...
Strange. Works in my case.
Are you sure that you are running the same version as you are building?
I am asking because step on this rake myself this morning:)

**Comment by bojanserafimov** [comment]
> Are you sure that you are running the same version as you are building?

What do you mean?

**Comment by knizhnik** [comment]
> > Are you sure that you are running the same version as you are building?
> 
> What do you mean?

I just mean that if you are doing `cargo build` then binaries are in `$NEON_HOME/target/debug/bin` and if `cargo build --release` - in `$NEON_HOME/target/release/bin`. If then you are using `neon_local` to start Neon and do not correctly specify path, then you launch old one.

I have tested both debug and release versions and it works in my case (it will be strange if it doesn't work because then same flate2 encoder/decoder are used and `GzDecoder::finish()` method is called which should flush everything.
So I am almost sure that you are testig some other version of the code.

**Comment by bojanserafimov** [comment]
>  flate2 encoder/decoder

flate2 works. async-compression doesn't. If you have a patch of async-compression working, send me a branch

**Comment by knizhnik** [comment]
I have committed my version to your branch!

**Comment by skyzh** [comment]
The issue is likely with the completion of the stream.

https://docs.rs/flate2/latest/src/flate2/gz/write.rs.html#90

gzip will need to write CRC after the stream completes. I don't see we are doing such things when using async-compression. Looking at async-compression example, we will need to call something like:

```
writer.shutdown().await?;
```

**Comment by skyzh** [comment]
PR ready for review -> https://github.com/neondatabase/neon/pull/4548

**Comment by bojanserafimov** [comment]
Closing, in favor of https://github.com/neondatabase/neon/pull/4912
