### ISSUE TITLE
Epic: proxy plan 

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#4693]
- [x] #5123
- [x] #5124

* credentials cache (smaller priority for now)
   * invalidation channel
   * replace proxy mgmt API with HTTP (now it is Postgres protocol)
   
 * Implement SCRAM channel binding

**Comment by petuhovskiy** [comment]
Just to remember, there is also `Console request failed with 400 Bad Request: endpoint is in transition` error happening in the authenticate flow. It can be fixed by retrying in the proxy or waiting in the control-plane, not sure what is better.

Ref:
- https://neondb.slack.com/archives/C04DGM6SMTM/p1689181928883869?thread_ts=1689181531.571319&cid=C04DGM6SMTM
- https://neonprod.grafana.net/goto/7QAwNNj4R?orgId=1
