### ISSUE TITLE
proxy: non-interactive transactions

### ISSUE THREAD

**Issue by conradludgate** [neondatabase/neon#4703]
perform a sequence of commands atomically within a transaction. see #4654

**Comment by skyzh** [comment]
will look into how we can design our API to fit with Prisma's batch SQL interface

**Comment by skyzh** [comment]
After looking into Prisma implementation, it seems that even if we added non-interactive txn APIs, we can hardly utilize it in Prisma.

* The goal for having SQL HTTP API is for people to use it directly in browser / in Vercel Edge Functions.
* Prisma's query engines are implemented in Rust and does not seem to provide a WASM binding https://github.com/prisma/prisma-engines/, which means that it's unlikely to run this in browsers.
* Therefore, we should think about who can use the API endpoint before we start working on this issue.

---

I have not looked carefully into the prisma client package itself. Probably we can find some ways to hack into it so that it does not need to call the Rust engine thing and we can make the client nodejs package directly call our HTTP API.

**Comment by skyzh** [comment]
after looking into prisma/client, they seem to have something called "data proxy" support. Neon HTTP endpoint is similar to that and I think I will need a week or two to fork Prisma and come up with a demo. https://github.com/prisma/prisma/tree/main/packages/client/src/runtime/core/engines/data-proxy
