### ISSUE TITLE
Support multiple keys for JWT validation

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#4897]
To make it possible to rotate keys, pageserver and safekeeper need to accept tokens signed by multiple keys.

**Comment by arpad-m** [comment]
I can work on this, unless someone else was already in mind.

**Comment by arpad-m** [comment]
Had a first look on the issue, there is a safekeeper/pageserver config.toml value for `auth_validation_public_key_path`. It has the path to the key's pem.

I see multiple possible designs:

* add a `auth_validation_public_key_paths` value which takes a list of paths to .pem files.
* make `auth_validation_public_key_path` optionally take a directory and have loading code perform a listing of the directory, and then add all files in it to the list of allowed keys

Live reload could be supported in both scenarios, either via a HTTP endpoint, or via notify watching the toml file, or the directory. In the case of reloading the entire configuration toml, I suppose some config params would support a live reload, while others wouldn't, and one would have to error if the toml is different in any params that don't support a live reload.

There is also this race condition issue where a reload might be triggered via the API while the write to the toml is ongoing. Attackers might potentially abuse this, if they can trigger reloads, and also have partial capabilities to set individual keys considered innocous, to maybe have the loading code not see some tail of the file because it is yet to be written by the writing code. For defense ideas, I guess one could use lock files or such, but imo it's also good to live with this for now. The reload endpoint would probably require highly privileged admin token access, so it's more something to worry about regarding escalation.

I guess the first step would be to implement one of the config designs, and the second to implement live reload.

**Comment by ololobus** [comment]
@shanyp will it be picked up by storage team in Q4? It will likely block signing keys rotation

**Comment by shanyp** [comment]
@ololobus what date in Q4 is this needed ? do we have the solution for key creation and distribution in place?

**Comment by ololobus** [comment]
> what date in Q4 is this needed?

I don't think that there is a deadline, just keep in mind that this will block the seamless key rotation as we cannot just add new key and start signing JWTs with, keeping running computes intact

> do we have the solution for key creation and distribution in place?

@SergeyMelnikov may know better, but iirc, we just add keys as k8s secret for console / cplane and somewhere in the ansible for storage. So at least for cplane it should be just a matter of configuration change in order to add two keys

**Comment by shanyp** [comment]
@jcsp what is the effort estimate for supporting tokens signed by multiple keys?

**Comment by jcsp** [comment]
Approx 1 week -- I  would go with Arpad's suggestion to allow the existing config to refer to a directory, and then add an HTTP API to ask the pageserver to reload from that directory.

**Comment by shanyp** [comment]
@ololobus lets sync once you will know when this will be worked from cplane side so we can have the work done in parallel

**Comment by ololobus** [comment]
There is no work left from the cplane side. It already supports a set of keys, so it can sign JWTs with the most recent one and verify with legacy keys. @nikitakalyanov is doing some final checks in all envs to check that we enforce auth everywhere we planned. Then I'm going to unlink this follow-up and close parent Epic

**Comment by arpad-m** [comment]
Made a PR: #5594

**Comment by shanyp** [comment]
@ololobus please have someone from cplane review this PR so we can understand if any more effort is needed here
