### ISSUE TITLE
Availability check fails if `neon.max_cluster_size` is reached

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#5001]
An alert fired last night, because availability-checker failed with this error:

```
could not execute operation: could not check project: db error:
ERROR: could not extend file because cluster size limit (3072 MB) has been exceeded
HINT: This limit is defined by neon.max_cluster_size GUC
```

This has happened at least once before. I unblocked it by increasing `neon.max_cluster_size` just for that check_availability operation, but likely it will fire again on the next availability-check. We need to find a permanent fix to prevent that from happening again. Perhaps make availability check exempt from the cluster size limit, or changing the check so that it never needs to extend a relation.

**Comment by knizhnik** [comment]
Right now availability_checker tries to create table (if not exists) and insert some data in it.
Frankly speaking I do not understand why availability means writability.
But IMHO the core problem is not with availability check, but with the attempt to limit logical database size, which is actually not a real logical size, i.e. number of records, but physical size - number of used pages.
It means that even if user will want to delete some rows to free some space, this attempt may failed because deletion in MVCC may also cause extension of relation.

**Comment by kelvich** [comment]
> Frankly speaking I do not understand why availability means writability.

to check that safekeepers work for this timeline

> It means that even if user will want to delete some rows to free some space

The same behavior as with finite disk space on HDD. Not ideal, but anything else is hard to implement and prone to edge cases. So far we haven't had much complains about releasing disk space, so looks like current model is not that bad. If we see complains, we always can rework our quotas.

We did a bit of investigation and looks like in both cases of that alert it was a first check operation that failed. So most likely the scenario here is following:
* user creates new project
* fills it with data till the quota exhaustion
* disconnects, project shuts down
* availability checker wakes project and fails to create table / add row

So we could create this table and row during the project initialisation and that should resolve the issue.

**Comment by kelvich** [comment]
@vk let's find someone to pick that up. Not super urgent, but can wake people at the night and seems not hard to fix.

**Comment by kelvich** [comment]
@vadim2404 let's find someone to pick that up. Not super urgent, but can wake people at the night and seems not hard to fix.

**Comment by hlinnaka** [comment]
>> It means that even if user will want to delete some rows to free some space
> 
> The same behavior as with finite disk space on HDD. Not ideal, but anything else is hard to implement and prone to edge cases. So far we haven't had much complains about releasing disk space, so looks like current model is not that bad. If we see complains, we always can rework our quotas.

See https://github.com/neondatabase/neon/issues/1245  for discussion on that.

**Comment by knizhnik** [comment]
> The same behavior as with finite disk space on HDD.

Yes, it is true. But it is much harder to exhaust space on Tb HDD rather than our 3Gb logical size limit.

> Not ideal, but anything else is hard to implement and prone to edge cases. 

IMHO, the currently used approach is the worst possible choice. Ideally there should be no limits at all and throttling or charging in case of exceeding some threshold. But I realise that nobody wants to discuss it once again, especially in context of this ticket.

> So we could create this table and row during the project initialisation and that should resolve the issue.

It can work. Not 100% fix, because even update of the single record in exited table can cause relation extension.
But probability will be close to 0.

The only problem - I do not know right place where this table can be created. Looks like it should be create project handler in control plane. 
But what about adding this table to Neon extension? Certainly in this case we should force creation of this extension. But may be it will be useful in any case? Also right now, `health_check` table is created in public scheme. Probability of name collision with some user's table is non 0. Hiding this table ion Neon extension and may be even placing it in dedicated scheme may exclude such collision.

**Comment by hlinnaka** [comment]
If the point is to test that streaming to safekeepers work, we could do something else that generates WAL but doesn't write to any relations. e.g.

```
select pg_logical_emit_message(true, 'neon', 'avail check');
```
The `true` means that it associates the message with an XID, which ensures that the commit waits for the WAL to be acknowledged by safekeepers.

**Comment by kelvich** [comment]
> select pg_logical_emit_message(true, 'neon', 'avail check');

Fair. Though I'd rather go in the opposite direction and tighten the check so that we can query pageserver for changed page (perhaps using special function in postgres to ignore shared buffers or some other hack). If it is too expensive we can decrease frequency. But the more stuff we can check there the better we are: we can find some issue while client is not connected yet.

**Comment by hlinnaka** [comment]
> > select pg_logical_emit_message(true, 'neon', 'avail check');
> 
> Fair. Though I'd rather go in the opposite direction and tighten the check so that we can query pageserver for changed page (perhaps using special function in postgres to ignore shared buffers or some other hack). If it is too expensive we can decrease frequency. But the more stuff we can check there the better we are: we can find some issue while client is not connected yet.

Also fair. Fetching pages from the pageserver is exercised every time the server starts up, because catalogs need to be fetched. Not the just-modified page, though.

**Comment by knizhnik** [comment]
> Though I'd rather go in the opposite direction and tighten the check so that we can query pageserver for changed page

IMHO it is overkill. We need to make modification, somehow invalidate shared buffer, request this modification from PS...And what is the goal?

> But the more stuff we can check there the better we are: we can find some issue while client is not connected yet.

If this check is done before client is connected, then we just increase start time, which is one of the most critical characteristics. If this check is done for already connected client, then probability that this check will detect some problem before client noticed it is very small.

May be I missed something - I never thought much about this problem, but I do not see much sense in this live checks at all. The main arbiter is client. If we think that node is alive, but client doesn't receive response in time, then it is actually dead. And visa versa, if our check shows that node is not alive, but client doesn't notice it, then there are no reasons to try to do something (restart node, report error,...). May be safekeepr at this moment is just restarting. And we decide because of the result of this check that node is not alive and we should restart it.

May be it is stupid idea. but communication between client and compute is done through the proxy. So we can easily detect when no response is received from compute within some interval. There may be completely no criminal in it - for example execution of some complex query may take arbitrary amount of time. But such delay can trigger more precise check.

**Comment by knizhnik** [comment]
So should I create a PR with replacing health_check table  with logical emit record?
Out seems to be the simplemest and most reliable solution...
All other suff can be discussed and addressed later.

**Comment by problame** [comment]
Can't the health check detect & ignore the "no space" error?

**Comment by vadim2404** [comment]
If we ignore the "no space" error, can it still be treated as a health-check?

**Comment by problame** [comment]
IMO availability check should mean: reads and writes behave as expected.
No space is what's expected if we're at size limit.

Of course if SK incorrectly returned "no space", the availability check wouldn't fire.

But, I think users would notice such a bug quite soon anyways.

So, I think ignoring "no space" is the right trade-off.

Perhaps @knizhnik can include this rationale in the PR / commit message.

**Comment by ololobus** [comment]
We now do several things
1. Unset `neon.max_cluster_size` during compute startup, so we should never hit it at start/configuration
2. We pre-create check tables, so most of the time we request the same page (using HOT-update path, iirc)
3. Konstantin commit got merged to ignore disk full error https://github.com/neondatabase/neon/pull/5010/files

I've run [this query](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22bkw%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22default%5C%22,%20container%3D~%5C%22compute-node%7Cneonvm-runner%5C%22%7D%20%7C~%20%5C%22Tenant%20disk%20is%20full%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) and do not see any messages `Tenant disk is full`, so it confirms 2. and that even if we ignore disk full errors, it's pretty error and we can always checks that

Although we can change the check flow -- that's a different story, so I'm closing this for now
