### ISSUE TITLE
`STORAGE_IO_TIME`: don't use `with_label_values` on the hot path

### ISSUE THREAD

**Issue by problame** [neondatabase/neon#5131]
Every VirtualFile::read, we waste time hashing the `op="read"` label here, plus locking and mutex overhead.

Do it like StorageTimeMetrics instead.

**Comment by duguorong009** [comment]
Hi, @problame 
I would like to take this issue!

Can you add more explanation to the issue?
I checked the files- https://github.com/duguorong009/neon/blob/main/pageserver/src/metrics.rs#L1042C12-L1042C30 and https://github.com/duguorong009/neon/blob/main/pageserver/src/virtual_file.rs
But, I am not sure what to do with those.

**Comment by duguorong009** [comment]
Hey, @problame 
So far, I've checked the codebase a bit.

I found that the [StorageTimeMetrics](https://github.com/duguorong009/neon/blob/main/pageserver/src/metrics.rs#L1051) are using the `get_metric_with_label_values` to get the histogram values.
On the other hand, [VirtualFile::with_file](https://github.com/duguorong009/neon/blob/main/pageserver/src/virtual_file.rs#L336) uses the `with_label_values`.
In the prometheus crate, I checked that `get_metric_label_values` is called inside the `with_label_values` call.
So, I am not sure what to do with these same helper functions.

Can you please elaborate more on the issue?

**Comment by koivunej** [comment]
Hmm I think the problem was that `StorageTimeMetrics` is actually not an interesting one, it should had said `SmgrQueryTimePerTimeline` or just the `BucketMetrics`. The `SmgrQueryTimePerTimeline` is a simpler version than `BucketMetrics`: https://github.com/duguorong009/neon/blob/7ba0f5c08d85aa8fd6ca9981f1857e3b832ab145/pageserver/src/metrics.rs#L640-L666

**Comment by koivunej** [comment]
If you want to take a stab at this, it would be a good performance fix for which we don't really have any github visible benchmarks. But it would be great anyways.

It might be that some of my guidance is off because of that `op: &str` not actually being a closed type yet, and you'll be the one to discover that. Please add me to any draft PRs and I'll try to give further help there, or feel free to ask questions on this issue.

**Comment by duguorong009** [comment]
Yes, I will definitely take this issue!
Thanks for help! @koivunej

**Comment by duguorong009** [comment]
@koivunej @problame 
Can you check the draft PR #5273 ?
Current issue I am facing is this code.
https://github.com/duguorong009/neon/blob/gr/storage-io-time-metrics-improval/pageserver/src/metrics.rs#L628
Rust compiler does not allow me to create `const` variable using non-const function, like `StorageIoTime::new()`.
The reason I created new const, global variable `STORAGE_IO_TIME_METRIC` is that I am not much sure where to create new instance of `StorageIoTime` struct.
I checked the `SmgrQueryTimePerTimeline` example, as @koivunej  recommended.
But, couldn't figure out the place of instantiating the `StorageIoTime` with above example.

**Comment by koivunej** [comment]
@duguorong009 replied here: https://github.com/neondatabase/neon/pull/5273/files#r1321283217

Otherwise this is looking good!
