### ISSUE TITLE
Postgraphile introspection fails to produce full schema

### ISSUE THREAD

**Issue by rfdrake27** [neondatabase/neon#5270]
## Steps to reproduce
Following successful connection to NeonDB and installation of postgraphile, the automatic generation of the schema will produce a schema with only functions. Tables, domains, and edges are all missing.

## Expected result
The same schema should be generated from a NeonDB database as you would expect for a vanilla Postgres DB.

## Actual result
The automatic generation of the schema will produce a schema with only functions. Tables, domains, and edges are all missing.

## Environment
Postgraphile v5.0.0
Node v18.16.0
NeonDB Postgres v15

The owner of the functions is the same as the tables. 

## Logs, links
-

**Comment by hlinnaka** [comment]
Weird. I have no prior experience with postgraphile, but it works for me:

1. First I created a new project on neon, connected t it with psql, and created two tables called "foo" and "bar".

2. I launched postgraphile per the instructions at https://postgraphile.org/news/2023-08-03-version-5-beta/:

```
~$ npx pgl@beta -P pgl/amber -e -c "postgresql://neondb_owner@ep-purple-sunset-a2h6sfjp.eu-central-1.aws.neon.tech/neondb?sslmode=require" -s public
The GRAPHILE_ENV environmental variable is not set; Grafast will run in production mode. In your development environments, it's recommended that you set `GRAPHILE_ENV=development` to opt in to additional checks that will provide guidance and help you to catch issues in your code earlier, and other changes such as formatting to improve your development experience.
Server listening on port 5678 at http://[::]:5678/graphql
```

3. I opened a browser to that URL. In the GraphQL Explorer, I can see the two tables:
![image](https://github.com/neondatabase/neon/assets/191602/e95dc870-e38e-41d4-8a45-9ce2705d3f0b)


I'm closing this issue, on the assumption that whatever the problem was, it's been fixed by now. Please reopen if you can still reproduce it.

(P.S. sorry for the delay, I noticed this report only now, when going through old issues..)
