### ISSUE TITLE
NeonDbError: db error: ERROR: prepared statement "s675205" does not exist

### ISSUE THREAD

**Issue by passgoco** [neondatabase/neon#5714]
## Steps to reproduce
Execute any insert query.

## Expected result
Queries execute correctly

## Actual result
NeonDbError: db error: ERROR: prepared statement "s675205" does not exist

## Environment
Neon cloud with autoscaling 1-7

## Logs, links
- is related to https://github.com/neondatabase/cloud/issues/7554

**Comment by passgoco** [comment]
After some investigation, it looks like pgbouncer is the problem. I switched from the pooled connection to the direct connection and this are working again

**Comment by edouard-blocktool** [comment]
Started seeing this in production since 4am PST today.

**Comment by edouard-blocktool** [comment]
START RequestId: 31e8caa3-a553-4b28-b972-526e760fb89b Version: $LATEST
2023-10-30T17:38:34.934Z	31e8caa3-a553-4b28-b972-526e760fb89b	ERROR	NeonDbError: db error: ERROR: prepared statement "s1803523" does not exist

Caused by:
    ERROR: prepared statement "s1803523" does not exist
    at /var/task/node_modules/@neondatabase/serverless/index.js:1530:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FilingService.listFilings (/var/task/.next/server/chunks/394.js:34:26)
    at async Promise.all (index 0)
    at async search (/var/task/.next/server/pages/api/search.js:213:34)
    at async handler (/var/task/.next/server/pages/api/search.js:264:25)
    at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapApiHandlerWithSentry.js:153:35 {
  code: '26000',
  sourceError: undefined
}
2023-10-30T17:38:34.934Z	31e8caa3-a553-4b28-b972-526e760fb89b	ERROR	NeonDbError: db error: ERROR: prepared statement "s1803523" does not exist

Caused by:
    ERROR: prepared statement "s1803523" does not exist
    at /var/task/node_modules/@neondatabase/serverless/index.js:1530:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FilingService.listFilings (/var/task/.next/server/chunks/394.js:34:26)
    at async Promise.all (index 0)
    at async search (/var/task/.next/server/pages/api/search.js:213:34)
    at async handler (/var/task/.next/server/pages/api/search.js:264:25)
    at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapApiHandlerWithSentry.js:153:35 {
  code: '26000',
  sourceError: undefined
}
2023-10-30T17:38:36.008Z	31e8caa3-a553-4b28-b972-526e760fb89b	ERROR	NeonDbError: db error: ERROR: prepared statement "s1803523" does not exist

Caused by:
    ERROR: prepared statement "s1803523" does not exist
    at /var/task/node_modules/@neondatabase/serverless/index.js:1530:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FilingService.listFilings (/var/task/.next/server/chunks/394.js:34:26)
    at async Promise.all (index 0)
    at async search (/var/task/.next/server/pages/api/search.js:213:34)
    at async handler (/var/task/.next/server/pages/api/search.js:264:25)
    at async /var/task/node_modules/@sentry/nextjs/cjs/common/wrapApiHandlerWithSentry.js:153:35 {
  code: '26000',
  sourceError: undefined
}
RequestId: 31e8caa3-a553-4b28-b972-526e760fb89b Error: Runtime exited without providing a reason
Runtime.ExitError
END RequestId: 31e8caa3-a553-4b28-b972-526e760fb89b
REPORT RequestId: 31e8caa3-a553-4b28-b972-526e760fb89b	Duration: 1294.55 ms	Billed Duration: 1295 ms	Memory Size: 1024 MB	Max Memory Used: 155 MB

**Comment by kelvich** [comment]
> ERROR: prepared statement "s1803523" does not exist

Looks like your are using prepared statements over pooled connections. That is not expected to work with the current `pgbouncer`: https://neon.tech/docs/connect/connection-pooling#connection-pooling-notes-and-limitations

There are active attempts to fix that on the pgbouncer side: https://github.com/pgbouncer/pgbouncer/pull/845 But it is not fully baked yet: https://github.com/pgbouncer/pgbouncer/issues/974

**Comment by edouard-blocktool** [comment]
If there's a prepared statement, it's done by vercel storage?

import { sql } from "@vercel/postgres";

export class FilingService {
  async listFilings(ticker: string, limit: number = 100): Promise<IFiling[]> {
    const { rows } = await sql<any>`
      SELECT id, path, ticker, form, period, filing_date
      FROM filing_file_2
      WHERE ticker = ${ticker}
      AND is_entrypoint = true
      AND (form = '10-K' OR form = '10-Q')
      ORDER BY filing_date DESC
      LIMIT ${limit}
    `;
    return rows.map(asFiling);
  }
}

**Comment by kelvich** [comment]
Ok, then the story is a bit different here. Serverless driver (`@vercel/postgres` imports `@neondatabase/serverless` -- you can see that in the backtrace) uses our http proxy instead of direct database connection. Http proxy uses extended postgres protocol which uses protocol-level prepared statements and proxy has it's own connection pool.

When you use serverless driver against `-pool` url you end up with a following configuration: `backend` -> `http proxy` -> `pgbouncer` -> `postgres`. And since `http proxy` uses prepared statements pgbouncer sometimes may return an error that you are seeing.

Quick fix: drop `-pool`, use direct postgres connection

Longer fix: that is a footgun and we should also fix that on our side. E.g. drop `-pool` when connection is done to http proxy. But keep it in the websockets case.

**Comment by edouard-blocktool** [comment]
Our database are managed by Vercel. If I understand correctly from the doc, the only way to move away from pooling is using something like this:

```
import { QueryResult, QueryResultRow, createClient } from "@vercel/postgres";

class SqlService {
  public async query<T extends QueryResultRow>(query: string, params?: any[]): Promise<QueryResult<T>> {
    const client = createClient();
    await client.connect();
    try {
      const res = await client.query<T>(query, params);
      return res;
    } finally {
      await client.end();
    }
  }
}
```

But then our performance goes to trash and we're not better off. API that used to be sub-1 second now take 16 seconds.

**Comment by kelvich** [comment]
With Neon you always have two endpoints to connect to, e.g. `ep-plain-thunder-3097180.eu-central-1.aws.neon.tech` and `ep-plain-thunder-3097180-pooler.eu-central-1.aws.neon.tech`. You can remove `-pooler` part from `process.env.POSTGRES_URL` and end up with the direct database connection.

I understand that it is a footgun, and no much of handles are exposed to you through Vercel. We'll follow up with a fix on our side, so that you don't have to do anything. Above is a temp fix.

**Comment by kelvich** [comment]
@passgoco @edouard-blocktool things are back to normal again and you can use pooled connections as well. We've traced this down to the backward-incompatible change we made. Turns out that pgbouncer works well with anonymous prepared statements and external people depend on that (originally we thought that it shouldn't work at all). Sorry for causing a trouble. We are going to invest some time into building a tests suite that checks compatibility with `@vercel/postgres` on end-to-end deployment.
