### ISSUE TITLE
future layer deletion can race with re-creation

### ISSUE THREAD

**Issue by arpad-m** [neondatabase/neon#5878]
See this thread [on slack](https://neondb.slack.com/archives/C0660LJT22J/p1700228454212409?thread_ts=1700227003.671649&cid=C0660LJT22J).

<s>1. a future image layer is created and uploaded
2. ps restart
4. the future layer from (1) is deleted during load layer map
5. image layer is re-created and uploaded
6. deletion queue would like to delete (1) but actually deletes (4)
    - delete by name works as expected, but it now deletes the wrong (later) version</s>

~~deletion can be delayed and might happen after re-creation has uploaded the layer file. Then, later on, the file is gone.~~

~~Another thread with more illustrative screenshot: https://neondb.slack.com/archives/C0660LJT22J/p1700230109306539~~

Edit: [see comment below](https://github.com/neondatabase/neon/issues/5878#issuecomment-1821321260) for what's going on.

cc @koivunej

**Comment by koivunej** [comment]
Uploads need to make sure there is no pending deletion for the name. Easy solution would be to delete a specific object version but we do not track that. I can't really see a quick fix. A test case would be easy to do.

**Comment by problame** [comment]
Summarizing [today's Slack discussion](https://neondb.slack.com/archives/C033RQ5SPDH/p1700561825100189?thread_ts=1700263700.548799&cid=C033RQ5SPDH) 

The symptom is the layer file that's referenced from index part but actually missing in the remote storage.

The intermediate cause is what @arpad-m  pointed out in the initial comment, i.e., the DELETE from load_layer_map and the PUT of the re-creating compaction get incorrectly reordered.

The root cause for that reordering is **not a bug in the deletion queue**, nor the persistence of the deletion queue. One might get that impression from [the initial Slack thread](https://neondb.slack.com/archives/C0660LJT22J/p1700228454212409?thread_ts=1700227003.671649&cid=C0660LJT22J). It's wrong. We don't have generation numbers enabled in prod yet, so, the deletion is neither deferred nor is the queue persistent across process restarts.

The real bug is one level higher, namely, in how the `remote_timeline_client` / `upload_queue`: the upload queue allows DELETEs and PUTs to run concurrently. It is the user's job to insert a barrier if they operate on the same keys and a certain order is required.

So, the solution here is to insert a barrier between the deletion and re-creation, so that deletion is guaranteed to happen before re-creation.

Here's an illustration of the upload queue that, depending on execution order, can lead to the symptom:

<img width="1149" alt="image" src="https://github.com/neondatabase/neon/assets/956573/8f9fc25f-e5e5-4b60-99be-07f0d51f6a8f">
