### ISSUE TITLE
Check that epoch_start_lsn is the same as backup_lsn in 'zenith.signal'

### ISSUE THREAD

**Issue by kelvich** [neondatabase/neon#594]

**Comment by petuhovskiy** [comment]
This issue isn't fixed, should be reopened. The problem is that theoretically we can have a race between several computes. That can happen if one compute will fetch basebackup for some `backup_lsn` and tries to start with it, but in parallel other compute can commit something to safekeepers which make starting with old basebackup incorrect.

**Comment by stepashka** [comment]
the only possibly remaining part here is to tweak somthing so that when mismatching LSN happens, not just the walproposer, but whole postgres instance should restart

**Comment by arssher** [comment]
done
