### ISSUE TITLE
Unsupported startup parameter in options

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/neon#6291]
Examples

```
unsupported startup parameter in options: search_path
unsupported startup parameter in options: lock_timeout
unsupported startup parameter: replication
```

**Comment by khanova** [comment]
This is an expected behavior. PGbouncer does not support (either because it's irrelevant for pooler or potentially problematic) most of the startup parameters.

Some of this errors (e.g. `unsupported startup parameter: replication`) is WIP on the PGbouncer side.

It's possible to specify in the config extra params (that brings a bit of the ocerhead) or specify to ignore some (basically reset user-specified params).

I suggest to add track of `extra_float_digits` since it's not suppose tohave a huge cardinality and there are 57 affected endpoints for the last 7 days.

**Comment by vadim2404** [comment]
Can we rewrite the error to the user that explains? [To bypass these parameters, use the `non-pooled` connection string] and provide the link to the this page
