### ISSUE TITLE
Garbage collect WAL segments locally before making timeline inactive

### ISSUE THREAD

**Issue by arssher** [neondatabase/neon#6403]
Local WAL segments might be not deleted until next compute restart if they hadn't been deleted before timeline got deactivated, as deleter works only for active tlis.

Found in
https://neondb.slack.com/archives/C04KGFVUWUQ/p1705654541324659

**Comment by petuhovskiy** [comment]
I looked at the logs, it seems that we noticed it in perftests because `WAL removal` task iteration is very long (around 10s is spent on a single timeline). If you multiply 10 seconds by a number of active timelines, it is much bigger than default 5 minutes of usual compute lifespan.

I think we should gradually move away from the background tasks that iterate over all active timelines. But for now, I'll create a PR with metrics for removal task to make the issue more visible.

**Comment by petuhovskiy** [comment]
Looked at some weekend metrics that we already have, PR with additional metrics is still in progress.

We indeed backed up more segments than deleted, found these metrics to show that (https://neonprod.grafana.net/goto/Qv1xaX5Sg?orgId=1).
<img width="1698" alt="image" src="https://github.com/neondatabase/neon/assets/8150127/435b63d7-d2b1-424e-9abb-1df3aff2320a">

**Comment by petuhovskiy** [comment]
After I added logs, this was reproduced on staging once again, but I have found only ~2 cases when WAL removal task took slightly more than 10s.

It seems that the full cause of why removal wasn't working was the following scenario:
- new branch was created
- compute was started
- client quickly inserted data into this branch (~10 segments of data)
- compute was suspended by inactivity after 5 minutes
- then, after some more time, new `remote_consistent_lsn` arrived from pageserver
- it was equal to `commit_lsn` and timeline became inactive instantly
- background `WAL removal` job wasn't able to catch timeline where it's both active and `remote_consistent_lsn` is high

So this issue is manifested only when `remote_consistent_lsn` update is delayed until compute is suspended. While compute was active, `remote_consistent_lsn` wasn't updated, and `WAL removal` couldn't make progress because of that.

**Comment by petuhovskiy** [comment]
Was deployed to prod
