### ISSUE TITLE
pageserver: delta layer's permit appends beyond S3 size limit

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#6624]
Under some circumstances, we can write >4GiB layer files, resulting in failures to upload to S3.

The size limit needs to be enforced at the point we append to a layer file: it's too late once we're trying to freeze the layer, or trying to upload it to S3.

**Comment by koivunej** [comment]
I had the idea we should check between walreceiver batches if we still have space.

I think this is what the mutable layermap access was meant to check all along, it could be optimized at the same time not to take the write lock unless it needs to flush.

Implementing this is not exactly straightforward due to needing to track the amount in bytes..

**Comment by jcsp** [comment]
Precursor: https://github.com/neondatabase/neon/pull/6639/files
https://github.com/neondatabase/neon/pull/6639/files#r1479510740

**Comment by jcsp** [comment]
PR is approved, undergoing benchmarking.

**Comment by jcsp** [comment]
Benchmarking was inconclusive.  Current bulk insert test results are noisy.  There is no evidencce of a regression.  Will merge today.
