### ISSUE TITLE
Reduce layer map locking on the read path

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#6833]
Currently, the read path (`Timeline::get` and `Timeline::get_vectored` when it merges) hold the layer manager read lock while accumulating the reconstruct data (includes on-demand downloads and disk IO). The non-vectored read path grabs the lock [here](https://github.com/neondatabase/neon/blob/feb359b45924252da4eb4863a6c92d970ab46958/pageserver/src/tenant/timeline.rs#L2446-L2447).

Locking for this long is not required. Instead, the read path could hold on to a `storage_layer::Layer` (introduced in https://github.com/neondatabase/neon/pull/4938) and only hold the lock while querying the layer map. The fix for the vectored read path will be similar, but slightly more involved. The search fringe must be updated to hold `storage_layer::Layer` instead of layer descriptions and the in-memory handles will need some thought as well.

**Comment by koivunej** [comment]
Just realized while looking at some logs ([slack thread](https://neondb.slack.com/archives/C033RQ5SPDH/p1710946891448839?thread_ts=1710771071.921179&cid=C033RQ5SPDH)), that compaction now needs to wait for on-demand downloads. This is a regression introduced with the `struct Layer` work. Before that, we released the read lock for layer downloading and switching.

Since no one has noticed this in quite some time, I don't think this is critical, but we should get it eventually fixed, so a slight boost to this issue.

What needs to be done:
- always drop the read lock before doing anything with the Layer

**Comment by VladLazar** [comment]
Update:
* Merged [PR](https://github.com/neondatabase/neon/pull/7217) for the normal read path
* PR for vectored read is ready to merge, but I'm holding it back for the next release

**Comment by VladLazar** [comment]
Both PRs merged. Releasing on the week of 2024-04-08
