### ISSUE TITLE
Bad log lines in `test_pageserver_max_throughput_getpage_at_latest_lsn`

### ISSUE THREAD

**Issue by VladLazar** [neondatabase/neon#6925]
Seen in: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6917/8054789794/index.html

```
2024-02-26T20:59:28.762188Z ERROR page_service_conn_main{peer_addr=127.0.0.1:52078}: query handler for 'pagestream 395d957dd5fb678ff640dfcccccc520c 819b20ff8d01a7b1308ae4a3e48f1935' failed: unexpected message: CopyFail during COPY
```

This seems to happen for the last few requests, so there's an issue with `pagebench` waiting for the outstanding requests.

**Comment by jcsp** [comment]
Pagebench uses the 'proper' API including CopyFail, which causes this to happen whereas it doesn't with ordinary postgres.

**Comment by jcsp** [comment]
Client intends to hang up instead of sending copyfail, but looks like that isn't always happening.

**Comment by jcsp** [comment]
@problame do we still have a benchmark disabled because of this issue?

**Comment by problame** [comment]
No, it was disabled because of https://github.com/neondatabase/neon/issues/6724 which has been fixed since.

If we want the benchmark running again, I can take the same approach as Vlad did in 

https://github.com/neondatabase/neon/blob/270d3be507643f068120b52838c497f6c1b45b61/test_runner/regress/test_pageserver_getpage_throttle.py#L17-L20

for this benchmark, then we can forget about this issue.

Alternatively (preferedly!), we could decide to invest time fixing this warning.
I still don't understand why it's happening.
Here's what the page_service client used by pagebench currently does (the comment gives context)

https://github.com/neondatabase/neon/blob/9a9d9beaeef393aa3ad8ba5b7700adfaab857126/pageserver/client/src/page_service.rs#L111-L137

**Comment by Bodobolero** [comment]
See https://github.com/neondatabase/neon/pull/8023
Trying alternative 1 mentioned above:

If we want the benchmark running again, I can take the same approach as Vlad did in

[neon/test_runner/regress/test_pageserver_getpage_throttle.py](https://github.com/neondatabase/neon/blob/270d3be507643f068120b52838c497f6c1b45b61/test_runner/regress/test_pageserver_getpage_throttle.py#L17-L20)
Lines 17 to 20 in [270d3be](https://github.com/neondatabase/neon/commit/270d3be507643f068120b52838c497f6c1b45b61)
 env.pageserver.allowed_errors.append( 
     # https://github.com/neondatabase/neon/issues/6925 
     r".*query handler for.*pagestream.*failed: unexpected message: CopyFail during COPY.*" 
 ) 
for this benchmark, then we can forget about this issue.

**Comment by problame** [comment]
Let's close this issue then?
