### ISSUE TITLE
lazy=true with live migration

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#7000]
While discussing on adding control plane support for #6907 we realized it might be harmful for live migrations. Current plan is to have a soft assertion in the closed source control plane migration utility preventing the `live-migration and lazy` condition, but control plane will not have any logic for filtering the options.

If we deem that lazy=true can only be harmful for live migrations, we should just ignore the option on pageserver.

Internal discussion: https://neondb.slack.com/archives/C03438W3FLZ/p1709541570480609

**Comment by jcsp** [comment]
@koivunej will follow up with control plane team: if CP is doing the right thing, we don't need to have similar logic on the pageserver side.

**Comment by koivunej** [comment]
control plane never sets `lazy_attachment=true`, only forwards it, so it always does the safe eager. Migration scripts *allow* the lazy attachment to be set to true.

**Comment by jcsp** [comment]
I think this should be fine: if someone uses lazy mode during a live migration, they'll just see that it takes longer for the destination location's LSN to catch up: that's okay, because we _want_ it to take longer, to avoid overwhelming the pageserver with excessive logical size calculations.

(Currently, the storage controller still doesn't use lazy mode during live migration, but it does always use it during all other tenant attaches)
