### ISSUE TITLE
Lots of CPU time spent in 'tracing'

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#733]
Commit 7216f2260909595e2e5f87b074b71c2ff7276ace introduced the 'tracing' crate, but I'm now seeing a lot of CPU time spent in tracing related functions, like Lsn to string formatting, in the 'test_bulk_insert' test. This 'info_span' in walreceiver.rs seems to be the biggest culprit:

```
                while let Some((lsn, recdata)) = waldecoder.poll_decode()? {
                    let _enter = info_span!("processing record", lsn = %lsn).entered();
                    ...
                }
```
It's called for every WAL record, and apparently the formatter we're using constructs the string even if no events end up being logged within the span. That seems dumb. I wish info_span was close to free, when the information isn't actually logged.

Perhaps write a custom tracing formatter that avoids the overhead?

**Comment by SomeoneToIgnore** [comment]
A few scattered notes:

* A good way to repro the case is by running the `test_bulk_insert` via `ZENITH_BIN=./target/release/ pipenv run pytest -s -k test_bulk_insert` or similar and run the profiler to get the frames.

* The actual issue is the `info_span!("processing record", lsn = %lsn)` formatting our `lsn` always, taking some notable CPU time (~30% of the loop in my case after running the test above), but that formatted `lsn` is not used anywhere in the test, since there's not actual logging happens.
The formatted `lsn` is still needed to be stored since span data can be exported externally on demand, but in our case seems more reasonable to calculate the formatting only when we need to

* There's already a way to manually defer the formatting with `field::Empty`, here are good docs on the topic:
https://github.com/tokio-rs/tracing/blob/a320f01597d28bfee52a2fefd4b31388dc76545c/tracing/src/span.rs#L1125-L1195

That is not very good in our case, since we don't know where in the loop we actually log first and setting the formatted value before every logging in every place could be even more CPU wasteful.

**Comment by LizardWizzard** [comment]
I think this might be relevant https://pingcap.com/blog/how-we-trace-a-kv-database-with-less-than-5-percent-performance-impact

**Comment by knizhnik** [comment]
It seems to be not only problem with formatting but in synchronization promitives used inside (rwlock).
At my notebook I got the following results (`create table t2 as select generate_series(1,10000000)` without safekeeper):

| info_span | Time (sec) |
| ------------- | ------- |
| main         | 33 |
| without lsn | 28 |
| commented | 20 |

version without lsn is: `let _enter = info_span!("processing record").entered();`
So may be just comment this info_span? Other seems too be called less frequently and so are not perfamance critical.

**Comment by hlinnaka** [comment]
Yeah, we'll have to comment it out, if we don't find a way to make it cheaper. There's no hurry though, that's a small change to make if/when we need to squeeze out the last bit of performance.

Or maybe put it behind a configuration option. The lsn information is very useful when debugging, so I would hate to get rid of it completely.

**Comment by shanyp** [comment]
@koivunej is this still relevant with recent span changes ?
