### ISSUE TITLE
test_slow_secondary_downloads is flaky

### ISSUE THREAD

**Issue by koivunej** [neondatabase/neon#7339]
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7337/8590699668/index.html#suites/231aea51ea102d83d3dae52232693454/fb064c6daca0d822
- https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7337/8590699668/index.html#/testresult/ed77bfd8434d18d0

Both fail with:

```
test_runner/regress/test_pageserver_secondary.py:652: in test_slow_secondary_downloads
    assert progress_1["layers_downloaded"] > 0
E   assert 0 > 0
```

This is the 4s case for `via_controller=True`. I'd expect the second assertion on line 661 (1s case) to be flaky, but not the 4s one.

**Comment by jcsp** [comment]
Looking back over the last 30 days, this hasn't failed again since the cases on 2024-04-07 in this ticket.

Looking at the test, it seems like it could fail if the test system was suuuuuper slow to the point that it couldn't download one layer in 4 seconds.  We could wrap this in a wait_until but that would have a timeout too, that in principle a test node could run slowly enough to violate.

I'm going to close this: we can re-open if it reoccurs, and modify the test to have some even more generous time bound
