### ISSUE TITLE
timeline ancestor detach: race on restart with ephmeral file cleanup

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#7830]
There is a race with the tenant restart at the end of timeline ancestor detach as exhibited by [report](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7795/9178199128/index.html#suites/a1c2be32556270764423c495fad75d47/5365321627e6d6d2/). Race concerns deletion of ephemeral files backing in-memory layers. In the report it appears as failed endpoint startup, because pageserver failed to load the layers for the timeline, because it failed to cleanup the ephemeral file.

Possible solution:

- clear out in-memory layers in a ShutdownMode::Hard -- maybe also carry gateguard in InMemoryLayer

Carrying a gateguard within InMemoryLayer seems correct, because otherwise we cannot guarantee that Timeline::shutdown "releases" the directory from all filesystem operations.

Non-tempting alternatives:

- do flush at the end of timeline ancestor detach caused tenant restart
    - would be slow and/or create small layers needlessly

**Comment by koivunej** [comment]
This is an interesting case, thanks for reporting.

At the end of timeline ancestor detach, we restart the tenant. This is pretty much only test case as far as I know which restarts only a single tenant while that tenant is ingesting. There is however a problem because ephemeral layer is being raced to deletion from two places:
- old tenant or timeline shutting down (arc is dropped)
- new tenant or timeline is starting up

This could be avoided by:
- having each InMemoryLayer or even VirtualFile carry a gate guard
    - VirtualFile carrying a gate guard does seem excessive
- dropping inmem layers at Timeline::shutdown
    - we must not drop any actual layer files, or shard splitting needs to be reworked
