### ISSUE TITLE
pageserver: tenant deletions after shard splits may leave some layers behind

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#8308]
Currently, the tenant delete API operates on a TenantShardId's prefix in the S3 bucket, and is called on each shard in the tenant by the storage controller.

If a tenant used to have a smaller number of shards, those older shards' objects in S3 will not be cleaned up during a delete.

The simplest way to fix this is to make the controller issue a deletion to the base tenant path (excluding shard suffix) after deleting all the shards.  If we make the pageserver's delete API omit the trailing `/` on tenant paths, this shouldn't require a new API.

**Comment by erikgrinaker** [comment]
NB: this is not the case for deletion of local data though, which only deletes the exact path. This will likely need a special case for the base tenant case.

We should make it explicit in the API that deletion of an unsharded tenant will implicitly delete any tenant shards.

**Comment by erikgrinaker** [comment]
Actually, we execute deletions via an arbitrary shard node, so we'll only delete local data on a single node anyway. Either we're fine leaking local data (and eventually evicting it), or we have to harden this by routing shard deletions via the relevant nodes.

@jcsp Should we just ignore the local data here (at least for now), as long as we're deleting it in S3?

**Comment by yliang412** [comment]
Before we do deletion in remote blob storage, the storage controller first schedule each shard in the tenant to be detached.

https://github.com/neondatabase/neon/blob/dcf7af5a16e253f2f01ae849c3e4d4d3e41510ff/storage_controller/src/service.rs#L2815-L2836

**Comment by yliang412** [comment]
I think instead of deleting all the `tenants/{tenant_shard_id}` paths, which look like `tenants/{tenant_id}-XXXX`, we want something that deletes all the the tenant shards. 

**Example**

We originally have an unsharded tenant with `<tenant_id>`. 

After running for a while, We do a shard split with shard count 4. We now have the following paths
```
<tenant_id>/...
<tenant_id>-0004/...
<tenant_id>-0104/...
<tenant_id>-0204/...
<tenant_id>-0304/...
```

Note that we still keep `<tenant_id>` since the new tenant shards may refer to some layers in the original unsharded tenant path.

Currently during deletion, we are not deleting the `<tenant_id>/...` path on S3.

**Comment by erikgrinaker** [comment]
I think we'll also need to clean up any stale shards. But removing `<tenant_id>` will [remove all paths with the same prefix](https://github.com/neondatabase/neon/blob/7cfd116856d07ab34a63be6c221cc7f9ffd92a58/pageserver/src/tenant/mgr.rs#L1353-L1363) -- both `<tenant_id>/` and `<tenant_id>-<shard_id>/`.
