### ISSUE TITLE
test_readonly_node_gc failure

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9098]
Example:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9065/10960582380/index.html#suites/3ccffb1d100105b98aed3dc19b717917/9bcad57acdbb1a2

```
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 24118 failed: FATAL:  [NEON_SMGR] [shard 0] could not read block 0 in rel 1664/0/2676.0 from page server at lsn 0/0155C018
DETAIL:  page server returned error: Bad request: tried to request a page version that was garbage collected. requested at 0/155C018 gc cutoff 0/15623F0
```

Different kind of error (https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9469/11444519440/index.html#suites/3ccffb1d100105b98aed3dc19b717917/2c02073738fa2b39):

```
2024-10-21T16:57:13.594920Z  WARN lsn_lease_bg_task{tenant_id=575f199ef1ae99b21fbe8d991d1368b6 timeline_id=0187ee35b0795f1d56d92c3d2525e3cf lsn=0/1562000}: Failed to acquire lsn lease: error connecting to server: Cannot assign requested address (os error 99) (attempt 7)
```

**Comment by jcsp** [comment]
@yliang412 can you work on this this week please?

**Comment by jcsp** [comment]
@yliang412 can you work on this this week please?

**Comment by yliang412** [comment]
Sounds good. I'm changing `test_readonly_node_gc` as part. https://github.com/neondatabase/neon/pull/9055 and I will make it ready for review today. Do we want to merge a quick fix before this?

**Comment by jcsp** [comment]
If the #9055 PR will fix this today/tomorrow, then no need to rush a fix for this.

**Comment by yliang412** [comment]
## Context

[Slack Discussion](https://neondb.slack.com/archives/C04DGM6SMTM/p1727200905422279)


When pageserver generates the basebackup for the compute, if the requested lsn is at beginning of the page, then it shifts to the first record.

https://github.com/neondatabase/neon/blob/5cbf5b45ae337cc643812a2e6bb76e6eb79142e4/libs/postgres_ffi/src/xlog_utils.rs#L112-L125

This would show as the following behavior in the log, where we would start the static compute at `0/155C000` but later in PG it is using the rounded-up LSN in the basebackup. 

```
2024-09-20T15:39:31.623761Z  INFO start_compute:prepare_pgdata: Starting read-only node at static LSN 0/155C000
...
PG:2024-09-20 15:39:31.856 GMT [150420] LOG:  starting with zenith basebackup at LSN 0/155C018, prev 0/0
...
PG:2024-09-20 15:39:35.588 GMT [151171] FATAL:  [NEON_SMGR] [shard 0] could not read block 0 in rel 1664/0/2676.0 from page server at lsn 0/0155C018
```

In this case, getpage requests will be done in a different lsn than the lsn that we request for leases and are not protected from GC.

## Solution

Make LSN leases also store the `normalized` lsn.

I'm leaning toward doing it on the pageserver side, so that compute_ctl does not need to carry `postgres_ffi`, and it will appear that it still obtains the lease at the original lsn.

**Comment by yliang412** [comment]
Reopened as `test_readonly_node_gc` starts failing again, but for a different reason: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9469/11444519440/index.html#suites/3ccffb1d100105b98aed3dc19b717917/2c02073738fa2b39
