### ISSUE TITLE
Allow layers to hold a range of segments

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/neon#931]
We will need to have layers that cover a range of segments, to deal with small relations efficiently. The requires changes to the Layer structs, to hold a range of SegmentTags instead of just one SegmentTag. That affects the way they store the page versions, as well as the interface functions like `get_page_reconstruct_data`.

We will need logic to partition the key space in a smart way. But as a very first step, let's smash together all system catalogs into one partition, and continue with the 1:1 mapping between relation and segment for everything else. That requires all the changes to Layer structs, and allows us to implement a smarter partitioning scheme later.

I'm thinking that we still divide the key-space into segments, with SegmentTag representing each segment, but allow a layer to cover a range of SegmentTags. An alternative would be to drop the SegmentTag notion altogether, and allow each layer to cover a range of (RelishTag, BlockNumber) directly. But I think the notion of SegmentTag is still useful.

**Comment by hlinnaka** [comment]
@patins, since you've worked on Image/DeltaLayers, VecMap and PageVersions and all that before, I think this is right up your alley.

**Comment by MMeent** [comment]
As I thought about before; we could potentially apply the concepts of consistent hashing here as well; where we consider the bitspace of [nspid (* ?), datid, relid, forknum, blocknum] as the hash, so that blocks of a relation are still generally located in the same segment / layer. Consistent hashing being chosen because that it is a well-understood sharding algorithm with N shard descriptors for N shards, instead of O(d) for d proportional to data.

It would probably be also useful to use a different ordering of these attributes (forknum between datid and relid) to put all visibility maps / free space maps / data relations together.

* I don't think we use / support meaningful different namespaces.

**Comment by bojanserafimov** [comment]
Looks done to me.
