### ISSUE TITLE
`test_local_only_layers_after_crash` is unstable with pg17 + debug mode

### ISSUE THREAD

**Issue by jcsp** [neondatabase/neon#9522]
Example failure:
https://neon-github-public-dev.s3.amazonaws.com/reports/pr-6560/11517666040/index.html#testresult/fbf43ff5314d0827/retries

```
AssertionError: the L1 reappears
assert False
 +  where False = <bound method NeonPageserver.layer_exists of <fixtures.neon_fixtures.NeonPageserver object at 0x7f0df800dac0>>(`TenantId("566ebf4c0a6d63ade2bf2f5d4724ccf3"), TimelineId("061903e7ed4a088b5dda9784992071fb"), DeltaLayerName(lsn_start=Lsn("0/14FA679"), lsn_end=Lsn("0/21C9111"), key_start=Key(key_int=33729647170896339747438627114713089), key_end=Key(key_int=33729647170896339765466219763729888)))
 +    where <bound method NeonPageserver.layer_exists of <fixtures.neon_fixtures.NeonPageserver object at 0x7f0df800dac0>> = <fixtures.neon_fixtures.NeonPageserver object at 0x7f0df800dac0>.layer_exists
 +      where <fixtures.neon_fixtures.NeonPageserver object at 0x7f0df800dac0> = <fixtures.neon_fixtures.NeonEnv object at 0x7f0df7fcd280>.pageserver
```

**Comment by jcsp** [comment]
@problame please can you take a look this week -- if it turns out to be something bigger than a faulty test assumption then please let me know and we can defer or reassign

**Comment by problame** [comment]
I have managed to reproduce this locally, not 100% reliably, but well enough.

With RUST_LOG=debug, in the cases where the test fails with `AssertionError: the L1 reappears
`, we see message

```
...:compact_level0_phase1: too few deltas to compact level0_deltas=3 threshold=999999
```

The threshold is initially set to `999999` here

https://github.com/neondatabase/neon/blob/5bd8e2363aabdbf52b88242293e09d017b677321/test_runner/regress/test_pageserver_crash_consistency.py#L28

but the test later sets it to 3

https://github.com/neondatabase/neon/blob/5bd8e2363aabdbf52b88242293e09d017b677321/test_runner/regress/test_pageserver_crash_consistency.py#L48

So why is it again `999999` later in the test, sometimes?

Browsing around in the log, the reason is that storcon calls `/location_config` , setting the tenant config back to what it knows, i.e., `999999` as specified at the beginning of the test.

So, I guess the insight is that `patch_tenant_config_client_side` is not useful anymore since storcon is the authority over tenant configs and may reconcile at any moment.

This test is not alone with that, there are several tests that use `patch_tenant_config_client_side` and sampling some of them, it seems they are just as naive about it as this test.

Two solution proposals:

1. Disable reconciliation in storcon
  a. by default, for all tests
  b. on a test-by-test basis - we can start doing it in all the users of `patch_tenant_config_client_side`
2. Replace `patch_tenant_config_client_side` with an API that talks to storcon instead.

**Comment by problame** [comment]
Also, when we fix this, let's address this note I took locally

```patch
-    # wait for us to catch up again
+    # TODO: the SK is down, so, this doesn't make any sense
     wait_for_last_record_lsn(pageserver_http, tenant_id, timeline_id, lsn)
```

**Comment by jcsp** [comment]
> Browsing around in the log, the reason is that storcon calls /location_config , setting the tenant config back to what it knows, 

ah ha!

> Replace patch_tenant_config_client_side with an API that talks to storcon instead.

This sounds right to me.  End state: the only tests that do pageserver-local stuff should be tests that are explicitly exercising lower level APIs (e.g. generations/migrations tests that check the primitives which storcon drives)
