### ISSUE TITLE
deletion executor <-> upload queue race

### ISSUE THREAD

**Issue by skyzh** [neondatabase/neon#9859]
as yet another observation at https://github.com/neondatabase/neon/pull/9844, deletion that gets persisted in the deletion list might be executed after tenant reattach, and we should ensure uploads of the same file happen after it.

**Comment by jcsp** [comment]
I think the fix here is going to be to avoid re-using the same generation, rather than trying to remember this stuff across `Tenant` lifetimes.  This might be pretty simple for ancestor branch detach if we make the detach API carry a new generation to be used in the tenant constructed after restart.

**Comment by skyzh** [comment]
okay, then I'll look into doing a generation bump for detaching the ancestor to fix this bug.
