### ISSUE TITLE
introduce checksums to ensure local and remote files are correct

### ISSUE THREAD

**Issue by stepashka** [neondatabase/neon#987]
Motication:

DoD:

Implementation thoughts:

**Comment by SomeoneToIgnore** [comment]
Besides validating the actual file checksums, it would be great to detect storage format changes too.
We keep `metadata` bytes in our `IndexPart` already, that contains the version of the file format it was uploaded with.

We can move the version to the `IndexPart` directly (as `disk_consistent_lsn` was moved too) and ensure that we maintain the actual format remotely and don't download the unsupported ones.

**Comment by stepashka** [comment]
looks like we need an RFC for this?

**Comment by LizardWizzard** [comment]
This issue is only about checksum validation during upload and download. RFC may be needed for applying page level checksums on other stages. E g during wal-redo.

The current state of remote checksums:

There is an old method for supplying checksums to s3 PutObject. It allows to pass content_md5 to PutObject invocation, but it has the following problem: to pass checksum to this request we need to read the whole file and calculate it before actual upload. This work is redundant and is not efficient in terms of memory consumption and disk access. So there is a new method. See aws [blogpost ](https://aws.amazon.com/ru/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/)about that. TLDR it uses HTTP trailer feature of chunked encoding to send checksum after the request body, so there is no need to calculate checksum in advance. Unfortunately this feature is [not yet supported](https://github.com/awslabs/aws-sdk-rust/discussions/539) by the rust aws SDK. So the decision was that checksums for remote data are more of a "nice to have" feature at that point so it is not feasible to workaround the issue and we can postpone it until it becomes available through the library interface

**Comment by stepashka** [comment]
closing this in favor of https://github.com/neondatabase/neon/issues/2784
